### ISSUE TITLE
Websocket Question

### ISSUE THREAD

**Issue by davidmoshal** [loadimpact/k6#1000]
Hi, I'm looking to stress test a system using websockets.
Specifically I'd like to know about error rates with different server configurations.

As I understand it, K6 is written in Go, using Goja JS interpreter + babel.js, 
ie: not representative of any real-world client.

So, my question is whether it's possible to have K6 control a real browser (eg puppeteer) and report on errors generated ?

**Comment by na--** [comment]
Hi @davidmoshal, you can't control a real browser with k6. In general, k6 scripts are very insulated from the environment they're running on, so you can't control other processes.

That said, I'm not sure in what way you find k6 websockets lacking and unrepresentative of real-world clients. They can certainly be improved (most notably by https://github.com/loadimpact/k6/issues/865#issuecomment-447031467), but even so, they should still be enough to stress test a system in a lot of cases.

I'm closing this issue, since github issues aren't [the best place](https://github.com/loadimpact/k6#need-help-or-want-to-contribute) for questions, but feel free to open a topic on the [community forum](https://community.k6.io/) for further discussion. Or, if you have specific change suggestions or bug reports, feel free to reopen this issue or open a new one.

**Comment by davidmoshal** [comment]
thanks
