### ISSUE TITLE
How to read stream of file in k6

### ISSUE THREAD

**Issue by d5gwsw** [loadimpact/k6#1002]

**Comment by d5gwsw** [comment]
In my project there is no .go file.Is there any other way to read the stream of in k6 in simpler way

**Comment by MStoykov** [comment]
I don't understand why you would need `.go` file - k6 *IS* written in Go but other than that no `.go` files are required. 
There is no **stream** api for k6, but you can just read the whole file and send it as file over http if this is what you need. Please take a look at the [http.file](https://docs.k6.io/docs/file-data-filename-contenttype) documentation although you can probably do it with only [http.post](https://docs.k6.io/docs/post-url-body-params).

**Comment by d5gwsw** [comment]
Actually  I want to pass the file stream to request body to my api. Later on this stream is used to further process

**Comment by MStoykov** [comment]
What you want is to send that pdf over http to your api, correct? In that case what I have proposed will work for you. 

The #612 PR was about reading big files in small parts .. unfortunately this would not work ... well in clustered execution and because of that was *not* merged.

**Comment by d5gwsw** [comment]
I tried this but I am always getting unathorised error because API needs stream input & using http.file we are passing binary file.
Is there any other way to pass file stream?

**Comment by na--** [comment]
@d5gwsw, what exactly do you mean by a file stream? Can you tell me what HTTP feature/RFC you specifically need? `Transfer-Encoding: chunked`?

**Comment by d5gwsw** [comment]
I need below input to my api. In without k6 I am using like this-
let filePath='D:\\sample.pdf'
 contentLength: fs.statSync(filePath).size,
 contentType: 'applicaton/pdf',
 stream: fs.createReadStream(filePath)

above code in typescript using node js.
k6 is not supporting fs.createReadStream. 

stream should be like this which I am getting through above code without k6:=
 '{"_readableState":{"objectMode":false,"highWaterMark":65536,"buffer":{"head":null,"tail":null,"length":0},' +
            //   '"length":0,"pipes":null,"pipesCount":0,"flowing":null,"ended":false,"endEmitted":false,"reading":false,"sync":true,' +
            //   '"needReadable":false,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"paused":true,"emitClose":false,' +
            //   '"destroyed":false,"defaultEncoding":"utf8","awaitDrain":0,"readingMore":false,"decoder":null,"encoding":null},' +
            //   '"readable":true,"_events":{},"_eventsCount":1,"path":"D:\Sample.pdf",' +
            //   '"fd":null,"flags":"r","mode":438,"end":null,"autoClose":true,"bytesRead":0,"closed":false}';

**Comment by na--** [comment]
I'm sorry, but k6 isn't built on top of Node.js and it doesn't support the Node.js APIs. **Some** JS libraries that rely on **some** node APIs may work when passed through browerify ([more info](https://docs.k6.io/docs/modules#section-importing-javascript-libraries)), but usually not the ones that require access to the file system. 

I don't know why in your case it's important to read the file as a stream, and why the `open()` function that k6 provides is insufficient, but you currently can't do that in k6. You can follow this issue to be informed when we introduce such functionality in k6: https://github.com/loadimpact/k6/issues/592

Also, I'll close this issue, since the github issues are not the [most appropriate place](https://github.com/loadimpact/k6/#need-help-or-want-to-contribute) to ask "how to" questions. A much more appropriate place would be the [community forum](https://community.k6.io/), or [as you've found out](https://stackoverflow.com/questions/55512122/how-k6-will-support-for-createreadstream-property-to-read-file-stream), Stack Overflow. If you have a specific feature suggestion for k6, other than streaming reading of files, feel free to open a new issue.
