### ISSUE TITLE
Support and examples for Azure AD (multi-tenant) authentication with k6 running as ACI containers

### ISSUE THREAD

**Issue by MedAnd** [loadimpact/k6#1009]
I'm currently evaluating replacing Visual Studio load testing projects with k6 on a large multi-tenant micro-services project, however I could not find examples on AzureAD and MSAL.js library authentication/integration and ACI hosting support.

- Each of the tests would need to authenticate with different AzureAD instances and load test REST API endpoints. 
- Execute load tests continually (e.g for 24 hours+) in Azure DevOps pipelines, in a distributed manner (support launching k6 as Azure Container Instances or Azure DevOps agents and remove once load tests are complete?) 

**Links**

https://docs.microsoft.com/en-au/azure/container-instances/
https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL-basics
https://github.com/AzureAD/microsoft-authentication-library-for-js

**Comment by ppcano** [comment]
@MedAnd I investigated a little how it could be done.

> Each of the tests would need to authenticate with different AzureAD instances.

I am not sure if `MASL.js` library will work in `k6` because of the [current limitations of JS libraries](https://docs.k6.io/docs/modules#section-npm-modules). 

`MASL.js` looks to be a utility to interact with the [Microsoft Identity Platform/Azure AD](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-overview#getting-started) and I think you can create an HTTP request in your script to authenticate the user to perform the requests to your REST API endpoints. 

According to [Microsoft docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-daemon-acquire-token#protocol):

> If you don't have yet a library for your language of choice, you might want to use the protocol directly

```
POST /{tenant}/oauth2/v2.0/token
```




> Execute load tests continually (e.g for 24 hours+) in Azure DevOps pipelines, in a distributed in a distributed manner  


The guide [How to integrate your k6 load tests with Azure Pipelines](https://support.loadimpact.com/4.0/guides/azure-devops-integration/) can provide valuable info on how to achieve that.

**Comment by MedAnd** [comment]
@ppcano - appreciate the follow-up! We tested use of MSAL in a simple load test and as you noted MSAL.js is meant for interactive use, not automated login as is required for load testing. 

I'm currently checking with the MS Azure AD team on the best way forward and will share an update here.

**Comment by simskij** [comment]
Hey there, @MedAnd !

Just wanted to follow up with you and see whether you actually got this working in the end? It seems like something that might benefit other k6 users as well.

Thank you in advance!

Best,
Simme

**Comment by MedAnd** [comment]
Howdy @simskij - almost forgot this request but a change of client meant I never implemented. Given it's almost been a year, maybe the team behind k6 have implemented Azure AD integration 🙂 ?

**Comment by simskij** [comment]
Closing this then. Thanks for replying!
