### ISSUE TITLE
Error sending data to influxdb

### ISSUE THREAD

**Issue by jonboydell-massive** [loadimpact/k6#1013]
Hi,

When I'm running a load test against a URL (GET) with a query parameter that constantly changes I eventually get the following error:

time="2019-05-02T10:08:41Z" level=error msg="InfluxDB: Couldn't write stats" error="{\"error\":\"partial write: max-values-per-tag limit exceeded (100027/100000): measurement=\\\"http_reqs\\\" tag=\\\"name\\\" value=\\\"https://some/url/here?param=ADNSADSADSADSADSA\\\" dropped=648\"}\n"

It seems though k6 is sending the whole URL as the name tag (including query string params), and Influx soon bursts it's max-values-per-tag limit.  I have changed this in InfluxDB to be unlimited.  But how do I get k6 to use a more likely value for the name tag?

**Comment by na--** [comment]
Hi @jonboydell-massive, take a look at this part of the k6 docs about how you can customize the `name` tag to be less variable: https://docs.k6.io/docs/http-requests#section-aggregating-results-for-http-requests

If you don't want to manually modify the `name` tags everywhere, which, as you've seen, by default are the same as the `url` tags, you have two other options. You can make k6 emit the `name` metric tag as an InfluxDB field (which isn't indexed and is what we do for `url` by default) instead of a tag (which is indexed). You can do that via the `INFLUXDB_TAGS_AS_FIELDS` environment variable. More info [here](https://docs.influxdata.com/influxdb/v1.7/concepts/schema_and_data_layout/#encouraged-schema-design) and [here](https://github.com/loadimpact/k6/blob/master/release%20notes/v0.21.0.md#influxdb-output-add-support-for-sending-certain-sample-tags-as-fields-585). 

Or you can disable the `name` system tag altogether, by running k6 with something like `k6 run --system-tags proto,subproto,status,method,url,group,check,error,error_code,tls_version script.js`. Unfortunately due to open bugs you currently can't specify the system tags via an [environment variable](https://github.com/loadimpact/k6/issues/768) or a [JS option](https://github.com/loadimpact/k6/issues/1010) :disappointed:
