### ISSUE TITLE
HTTP Requests in the init context

### ISSUE THREAD

**Issue by liclac** [loadimpact/k6#103]

**Comment by uppfinnarn** [comment]
Whoops, hit Create too fast.

Sometimes, it may be useful to preload data (eg. using [https://github.com/marak/Faker.js] via [faker.hook.io](http://faker.hook.io)), but right now, you can only make HTTP requests inside a VU context.

This doesn't work:

```js
import http from "k6/http";

let res = http.get("http://example.com/data.json");
if (res.status != 200) {
    throw new Error("couldn't preload data");
}
let data = res.json();

export function default() {
    // ...
}
```

Instead, you have to load the data once per VU, like this:

```js
import http from "k6/http";

let data = null;

export default function() {
    if (!data) {
        let res = http.get("http://example.com/data.json");
        if (res.status != 200) {
            throw new Error("couldn't load data");
        }
        data = res.json();
    }

    // ...
}
```

Is this something we want to support? Maybe we should extend `open()` to read URLs instead? Or maybe the current workaround really is the best solution? (Notably, it failing will cause the VU to retry, rather than making the test fail to start.)

**Comment by micsjo** [comment]
Setup/tear down loading data and sundry is a prevalent pattern. And definitively very useful. As it stands data can be loaded from files but no other actions from requests.

Short answer: yes.

**Comment by liclac** [comment]
`open()` can read URLs the same way `import` does in the js2 runner.
