### ISSUE TITLE
 Specifying both duration and iterations is deprecated and won't be supported in the future k6 versions

### ISSUE THREAD

**Issue by arswaroop** [loadimpact/k6#1058]
Hello,
I am getting such warnings if i put arguments for iterations, users or duration. Can i know what will it be in future iterations, I didn't find any docs about this change on the website.

**Comment by na--** [comment]
@arswaroop, that warning may be a bit premature and unnecessary, but it was added in k6 because we plan to make some major improvements (and, unfortunately, some breaking changes) to the way k6 execution and scheduling of VUs work. You can find more details in the [following WIP pull request](https://github.com/loadimpact/k6/pull/1007), but in short, in the k6 version following the next one, the execution will be a lot more flexible and feature-rich.

The basic idea is that the current `iterations`, `duration` and `stages` options will still be usable - they will just act as shortcut options for the new schedulers/executors. So if you use `iterations`, you'd get the `shared-iterations` executor, and if you use `duration`, you'd get `constant-looping-vus`, etc. 

The breaking changes stem from the way k6 currently supports multiple different conflicting options. It is somewhat buggy and so those warnings were added in k6 v0.24.0 to prepare users for the breaking changes. For example, it makes no sense to specify both `duration` and `stages`, but k6 currently doesn't forbid it...

But I think I was actually overzealous in removing support for simultaneously using the `iterations` and `duration` shortcut options... Those two shortcuts could co-exist without issues, and the `shared-iterations` executor from that PR actually supports them. `k6 run --iterations 10 --duration 20s --vus 5` would produce something like this:
```js
export let options = {
  execution: {
    default: {
      type: "shared-iterations",
      vus: 5,
      iterations: 10,
      maxDuration: "20s",
    }
  }
};
```

I'll remove this specific warning as part of https://github.com/loadimpact/k6/pull/1057 (so it gets released with k6 v0.25.0 in the next week or so), and I'll make the change to https://github.com/loadimpact/k6/pull/1007 as well, so it gets in the actual new executors.
