### ISSUE TITLE
Whether K6 supports TLS 1.3 ?

### ISSUE THREAD

**Issue by hgkiller** [loadimpact/k6#1061]

**Comment by na--** [comment]
It does, but not by default. Judging by the [Go `tls` documentation](https://golang.org/pkg/crypto/tls/), you need to set the `GODEBUG` environment variable to contain `tls13=1`. I tried executing the following script:
```js
import http from 'k6/http';
import { check } from 'k6';

export default function () {
    let resp = http.get("https://www.howsmyssl.com/a/check");
    check(resp, {
        "status is 200": (resp) => resp.status === 200,
        "tls 1.3": (resp) => resp.json().tls_version === "TLS 1.3",
    });
};
```

with k6 v0.24.0 by running `GODEBUG=tls13=1 k6 run zt.js` and that worked, but only because of the environment variable... It seems like in Go 1.13 (the next Go version that would probably be released in August), there won't be any need to use the environment variable (https://github.com/golang/go/issues/30055), but maybe we'll opt-in before that...

**Comment by na--** [comment]
Whether we wait for Go 1.13 or do the `os.Setenv("GODEBUG", os.Getenv("GODEBUG")+",tls13=1")` hack, we'd also need to edit this file: https://github.com/loadimpact/k6/blob/2a2fe2cc665e0d2b818c4f3ca7ce4fc9a5821294/lib/tlsconfig_go1_8.go#L30-L43 

To add explicit support for tls 1.3 in the k6 options like this:
```js
export let options = {
    tlsVersion: {
        max: "tls1.3",
    }
};
```
And somewhat connected issues that we probably should fix at the same time: https://github.com/loadimpact/k6/issues/1055, https://github.com/loadimpact/k6/issues/904
