### ISSUE TITLE
Using proxy for Insights

### ISSUE THREAD

**Issue by micsjo** [loadimpact/k6#1062]
Using k6 locally in a restricted network and sending data to Load Impact Insights or the "-o cloud" option is a very good solution.

However, restricted network often means internet access (if any) is usually by proxy.

We would like to have a way to specify a proxy for the cloud (or Insights) output only that will not impact the requests generated.

**Comment by na--** [comment]
It should be fairly simple to just add a proxy [config option](https://github.com/loadimpact/k6/blob/master/stats/cloud/config.go) for the Load Impact Insights output, via a `K6_CLOUD_PROXY` environment variable or something like that. But then, are we going to have to repeat this exercise for every single output, since it could be argued that there's a similar use case for them as well? That would definitely be cumbersome and would exacerbate the current configuration issues (https://github.com/loadimpact/k6/issues/883, https://github.com/loadimpact/k6/issues/587)...

A workaround (that's also far from ideal) when we have the [custom transports](https://github.com/loadimpact/k6/issues/1045#issuecomment-501150436) would be to set a global proxy via `HTTP_PROXY` environment variable (that would be used by the outputs) and an explicit no-proxy transport for the actual load test.

**Comment by micsjo** [comment]
You could honor the NO_PROXY header as well, such as curl does it [curl proxy headers](https://ec.haxx.se/usingcurl-proxies.html)

**Comment by na--** [comment]
Hm it actually seems like we already do! We [use](https://github.com/loadimpact/k6/blob/c85438949d00c2ca8a89d04b2837bb087a3d3201/js/runner.go#L163) the [`http.ProxyFromEnvironment`](https://golang.org/pkg/net/http/#ProxyFromEnvironment) and it seems to support `NO_PROXY`:
>  ProxyFromEnvironment returns the URL of the proxy to use for a given request, as indicated by the environment variables HTTP_PROXY, HTTPS_PROXY and **NO_PROXY** (or the lowercase versions thereof). HTTPS_PROXY takes precedence over HTTP_PROXY for https requests.
> ...
> A nil URL and nil error are returned if no proxy is defined in the environment, **or a proxy should not be used for the given request, as defined by NO_PROXY.**

**Comment by micsjo** [comment]
I noticed when I was looking into the code that you were using the standard golang implementation for the proxy settings which includes the NO_PROXY setting. I have just validated that it works as expected.


So this issue is simpler than fixing code, it's apparently enough to fix the documentation :-)

**Comment by na--** [comment]
Yep, tagged it as such :+1:  :smile: Thanks again!

**Comment by pawansinha0612** [comment]
@micsjo @na-- I am exactly having the same issue, If this is working for you guys. can you please help me with the code. I have my k6 scripts all in JS, now where should i incorporate ProxyFromEnvironment. please help.

**Comment by na--** [comment]
Closing this in favor of https://github.com/loadimpact/k6-docs/issues/74, given that the docs now live in their own repo.
