### ISSUE TITLE
Request is 400 in k6 but 200 in postman

### ISSUE THREAD

**Issue by arswaroop** [loadimpact/k6#1072]
Hey,

I am using k6 load testing for a project and I came across an issue. For all other APIs, it works fine but one endpoint is giving 400 via k6 which is a success in Postman. Refer below screenshots

![image](https://user-images.githubusercontent.com/41299771/60815265-41401b80-a165-11e9-8a1b-1fbe2615a927.png)

Postman
![image](https://user-images.githubusercontent.com/41299771/60815312-587f0900-a165-11e9-9a73-fc2751578717.png)

Let me know if I am doing something wrong.

**Comment by na--** [comment]
In short, [`http.get()`](https://docs.k6.io/docs/get-url-body-params) doesn't support sending a request body, it has only 2 parameters: the URL and the [request params](https://docs.k6.io/docs/params-k6http). Use the generic [`http.request()`](https://docs.k6.io/docs/request-method-url-body-params) instead :smile: 

I think the HTTP RFCs don't explicitly forbid bodies for GET requests, but in practice most HTTP servers either ignore those bodies or consider them an error. The reason for omitting the `body` parameter in `http.get()` in k6 probably was that it would save some user effort, because it wouldn't have been used by 99.9+% of users. And since in k6 `http.get(url, params)` is basically a shortcut for `http.request("GET", url, null, params)`, you should be able to use the `http.request()` method to make GET requests with a body:

```js
import http from "k6/http";

export default function () {
    let resp = http.request("GET", "https://httpbin.org/anything", "test");
    console.log(resp.body);
}
```

**Comment by arswaroop** [comment]
That did work. Thanks !!
