### ISSUE TITLE
help: what does the exact means of vus(virtual users)?

### ISSUE THREAD

**Issue by breezelxp** [loadimpact/k6#1088]
Hi everyone:
    I'm a new one, and I'm really do not understand the exactly meaning of vus. I have already read docs here: https://docs.k6.io/docs/welcome .
    Unfortunately, I can not find the answer.
    Does it means the QPS? current request?
    Any information is helpful, thanks.

**Comment by na--** [comment]
You can read more information about VUs and how k6 works in the github README [here](https://github.com/loadimpact/k6#running-k6) and [here](https://github.com/loadimpact/k6#overview), but in short, each k6 virtual user is an independent JavaScript runtime that is looping through the exported `default` function.

I'll close this issue, since the [community forum](https://community.k6.io/) is a more [appropriate](https://github.com/loadimpact/k6#need-help-or-want-to-contribute) place to ask this types of questions. We try to keep the github issues mostly focused on bugs and feature requests and things like that.

**Comment by breezelxp** [comment]
> You can read more information about VUs and how k6 works in the github README [here](https://github.com/loadimpact/k6#running-k6) and [here](https://github.com/loadimpact/k6#overview), but in short, each k6 virtual user is an independent JavaScript runtime that is looping through the exported `default` function.
> 
> I'll close this issue, since the [community forum](https://community.k6.io/) is a more [appropriate](https://github.com/loadimpact/k6#need-help-or-want-to-contribute) place to ask this types of questions. We try to keep the github issues mostly focused on bugs and feature requests and things like that.

thanks
