### ISSUE TITLE
Gaps in reports

### ISSUE THREAD

**Issue by tkdeshpande** [loadimpact/k6#1100]
Running test with InfluxDb and Grafana shows gaps in reports.
![gaps](https://user-images.githubusercontent.com/6124796/62407491-e8409780-b5eb-11e9-8064-4876334daa2f.png)
This happens for any test that lasts an hour. I've tried atleast 5 times and have gaps in each one.
The reports become un-usable because of the gaps and my organisation is seriously looking for other options if this doesn't work out.
Please help!

**Comment by MStoykov** [comment]
Can you provide us with some logs from the execution of k6? If something went wrong k6 would've logged it ;) 

Maybe influxdb is being overload as in #1060 ? Maybe you are hitting [the body size limit of influxdb](https://community.k6.io/t/413-error-when-writing-data-to-influxdb/100)? But in all cases more info would be needed to debug your problem.

**Comment by MStoykov** [comment]
After some more investigating I am pretty sure this is because of k6 fails to send the metrics to influxdb and it doesn't retry.
 So if you are hitting the body size limit or any other kind of limit, while you will get an warning in the k6 terminal you won't get your data. Can you check the k6 execution logs and see if any error/warning messages are emitted ?

Looking at the code I am going to do a lot of changes so maybe I will try to add some retry logic akin to the [cloud output ](https://github.com/loadimpact/k6/blob/master/stats/cloud/client.go#L97-L110).

**Comment by tkdeshpande** [comment]
@MStoykov : Thanks a lot for looking into it. I have tried to find logs related to this for a while but couldn't find anything. 
It very well looks like a data loss issue for now which makes the InfluxDB and Grafana integration unusable.

Thanks again for the support!

**Comment by MStoykov** [comment]
Can you try to build from #1113 and test with it ?

**Comment by tkdeshpande** [comment]
> Can you try to build from #1113 and test with it?

Sure @MStoykov ! Thanks a lot for the help! I will update you soon.
