### ISSUE TITLE
localhost connection refused, but 127.0.0.1 is not

### ISSUE THREAD

**Issue by yihuaf** [loadimpact/k6#1109]
Trying out k6 with a simple post request to a server listening on local port. When I set the host to localhost in the http.post, I got `tcp [::1]:8080: connect: connection refused`. The error goes away when I switch to `127.0.0.1`. wrk and other tools handles `localhost` just fine, so it's likely not a system issue, but k6 specific.

**Comment by sniku** [comment]
@yihuaf your network is likely configured in a way that gives you both IPv6 and IPv4 addresses for localhost. 
Most latest Linux distributions are set up this way. What happens when you `ping localhost` do you get a response from IPv4 or IPv6? 

On my Debian machine default is IPv6. See the screenshot below. 

![08_08_2019__21:48:49](https://user-images.githubusercontent.com/442646/62733298-94d4ac00-ba26-11e9-997a-b2a510cb92c0.png)

You can either reconfigure your `/etc/hosts` or be more explicit, and use `127.0.0.1` if you want IPv4.

**Comment by yihuaf** [comment]
Aha, thanks. I think that's exactly the issue.

**Comment by SebastianStehle** [comment]
I have the same issue with Windows. The problem is that right now I cannot move to the IP address because i have a certificate that I need to use. It works fine for the browser and postman and other clients, just k6 refuses to connect.

**Comment by na--** [comment]
@SebastianStehle, do you think it's an IPv6 issue in your case as well?

**Comment by SebastianStehle** [comment]
I don't know ... i tried to add an entry to the hosts file but it does not work. I also do not understand how it can be the problem, to be honest

**Comment by SebastianStehle** [comment]
I was digging into the code and first I thought it is just a simple bug or so and found this one:

https://stackoverflow.com/questions/28376472/golang-http-post-error-connection-refused

But it is mentioned that it is solved in go, so I tried to build it myself, but no luck. Then I made a simple test with go, which works fine.

**Comment by na--** [comment]
@SebastianStehle, k6 is written in Go, and does things on top of Go's `net` stdlib package, so it can measure the traffic it generates. This problem can be caused by a number of things, even if all other tools can make the requests successfully... :disappointed: So, I'm trying to diagnose the issue and need your help to do that. 

For some reason, if you can make a request to `https://127.0.0.1`, but not to `https://localhost`, then it means that either k6 can't resolve `localhost`, or it resolves it to something that it has issues connecting to, or something completely weird is going on. Go can make IPv6 requests, so k6 _should_ also be able to make them, but we haven't really tested that, so it might have been the cause.

Can you share more details about your environment and the _exact_ error you're getting? Which k6 version are you using (i.e. what's the full output of `k6 version`), how are you using it (i.e. did you install it the .msi package, installed chocolately, downloaded github release, docker container, linux binary through WSL, etc.), which version of Windows are you using, any other pertinent details? And what's the full text of the error k6 is giving you?

Also, as temporary a workaround until we figure out the root cause of the issue, you might consider using the [`insecureSkipTLSVerify` k6 option](https://k6.io/docs/using-k6/options#skip-tls-verification) with `127.0.0.1`. Since you're making localhost requests, there aren't really any security issues with that, though, depending on how the app you are load testing is written, you might have other issues with cookies, redirects, etc. if it expects `localhost` as the domain.

**Comment by SebastianStehle** [comment]
It seems that k6 makes the request to ipv6 and my server was only listening to ipv4. I have it solved now by listening to ipv4 and ipv6, but I think it should work out of the box. 

I have used the latest version from today and have built it myself. Before I was using v0.26.2 from the MSI. I have also tested the insecure tls fix, but it does not help. There are no cookies or or redirects.

What is strange though is that it works with a normal http call from a golang program. I am not a golang developer myself, but I tested this:

```
package main

import (
	"fmt"
	"log"
	"net/http"
)

func main() {
	tr := &http.Transport{
		MaxIdleConns:       10,
		IdleConnTimeout:    30 * 60,
		DisableCompression: true,
	}
	client := &http.Client{Transport: tr}
	resp, err := client.Get("https://localhost:5001")

	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("HTTP Response Status:", resp.StatusCode, http.StatusText(resp.StatusCode))
}`
```

I have also tested

```http.Get(...)```

 and 

```
client := &http.Client
resp, err := client.Get("https://localhost:5001")
```

All three alternatives worked just fine. I really think that is an ipv6 vs ipv4 problem but I don't understand why this problem only exists in k6.

**Comment by na--** [comment]
Because, as I said, we do some things in our [network connection code](https://github.com/loadimpact/k6/blob/master/lib/netext/dialer.go#L70), that on a second glance are probably very... not-smart :man_facepalming: So, this is definitely a k6 IPv6 bug, we'll open a new issue as soon as we have the full picture. Thank you for bringing this to our attention!

**Comment by na--** [comment]
@SebastianStehle, you can follow https://github.com/loadimpact/k6/issues/1537, I didn't want to reopen this issue, since the problem is not only with localhost :disappointed:
