### ISSUE TITLE
Maintain list of officially supported JS libraries

### ISSUE THREAD

**Issue by imiric** [loadimpact/k6#1123]
In a recent meeting the k6 team discussed the possibility of making certain JS functionality, like UUID or random data generation, part of k6 itself. Since we don't want to add more bloat to core, we agreed that it's preferable to keep these as external libraries, as they're currently used.

That said, having a list of validated and officially supported JS libraries, along with some real-world examples, would help users get started writing scripts quickly, without having to search and test different libraries on their own.

This issue is to consider some of the more popular libraries used, like [uuid](https://www.npmjs.com/package/uuid) and [faker](https://www.npmjs.com/package/faker), test and validate them internally, document their use and publish the documentation.

This is similar to what's currently at https://jslib.k6.io/, so either expand that or publish on https://docs.k6.io/.

**Comment by na--** [comment]
I'm thinking that we might also use whatever examples of these libraries we include in the documentation as a CI test suite, to ensure that that we actually continue to support these libraries in the future as well, or at least to be aware when there's an issue - either because of a new k6 version or a new library version.

**Comment by MStoykov** [comment]
I am closing this as this has been done for quite some time now
