### ISSUE TITLE
Webpack & default module imports

### ISSUE THREAD

**Issue by johnrom** [loadimpact/k6#1159]
Hello everyone, first thing. This library is awesome. I've tried a bunch of different libraries to integrate in CI and this one is blowing my mind!

I'm running a webpack build so I can use TypeScript and load some helper methods from a website build. It's working very well, but with one especially time-consuming caveat. No matter what I did, I couldn't get `k6` to recognize the default import that webpack exports via UMD or CommonJS (libraryTarget: commonjs or commonjs2 or commonjs-modules). I fought for hours with webpack, only to find out it was working as expected when I created a separate file and imported it. Trying to run the compiled file directly results in: `ERRO[0000] script must export a default function        -`.

I don't know much about Go, so I'm not much help on that front, but it looks like you guys use a JS parser called Goja and call `exports.Get("default")`. For some reason, this doesn't seem to work with Webpack's `WebpackUniversalModuleDefinition` initialization. It might be that I should open an issue upstream, but I figured I'd start here.

The workaround is, I created a second javascript file, and export the imports from the built file. It's not ideal, but it works.

`index.js`:

```js
// note importing default works here, so I think it should also work for k6
import VuScript from "./dist/k6-scripts.js";
import {
    setup as setupInner,
    options as optionsInner 
} from "./dist/k6-scripts.js";

export const options = optionsInner;
export const setup = setupInner;
export default VuScript;
```

`webpack.config.js`:

```js
const path = require('path');

module.exports = () => {
  return {
    entry: { 'k6-scripts': './src/k6-scripts.ts' },
    node: { fs: 'empty' },
    target: "node",
    mode: "production",
    resolve: { extensions: ['.ts', '.js'] },
    output: {
      path: path.resolve(__dirname, 'dist'),
      libraryTarget: 'umd',
    },
    externals: [
      /^k6(\/.+)?$/,
    ],
    module: {
      rules: [
        {
          test: /\.ts$/,
          include: [/src/, /MyApp/],
          loader: "babel-loader",
          options: {
            presets: [
              ["@babel/preset-env", {
                modules: false
              }],
              "@babel/preset-typescript",
            ]
          }
        },
      ]
    }
  }
};
```

`package.json`:

```json
  "scripts": {
    "k6": "npx webpack && k6 run ./index.js"
  },
```

Then just `npm run k6`

**Comment by MStoykov** [comment]
Hi @johnrom, glad you like it, but k6 is not a ... library it's an application. I am saying this mostly to make it clear that k6 is a separate application written in Go using the Goja (also written in Go) JS VM and not some library that is run through node.js as this is common misconception. Although it looks like you are not under that assumption, I wanted to make it clear at least for other people reading the issue.

That aside ... I don't know what exactly in the whole picture is tripping you, but as mentioned in the [documentation](https://docs.k6.io/docs/test-life-cycle):
> Scripts must contain, at the very least, a default function - this defines the entry point for your VUs, similar to the main() function in many other languages:

This is because the way k6 currently works (in simple terms) is that it calls that function over and over again for either a set amount of times in parallel (if more than 1 VU) or for a given amount of iterations (again maybe in parallel). By default if you haven't specified anything it will do 1 iteration. 
This means that for anything to work you need a `default ` function. As far as I understand your code just doesn't export one which is the reason you need a separate file.  If you  add `export default VuScript;` in your k6-scripts.js it will probably work ;). You might need to change to `commonjs` and outping for `web` instead of `nodejs` as well. 

Shameless plug: I have a [small project](https://github.com/MStoykov/k6-es6) showing how to use webpack with k6 with the idea to extend it to use typescript and other features of webpack in order to show people that it's possible. If you want I am taking PRs and ideas. And maybe you can share you findings and tips in a blogpost or something ;)

**Comment by johnrom** [comment]
@mstoykov the webpack export process does export a default function if I provide a default function. However, it is sort of magic. I understand that k6 is not a node library. My concern is that Goja doesn't evaluate the file and determine if it receives an object with `.default`, which is how I understand the requirements of UMD to be written. Instead, I think, if I had to guess, the check is whether or not the text `export default` exists in the file. Basically, webpack in its various forms, but I will use UMD target as an example because it is what I have implemented above, exports a function that is run when a file is loaded.

```
(function MyInitializationFunction() {
   return {
        default: __webpack__default__or_whatever_
    }
})()
```

My guess is that Goja doesn't actually run the javascript to test if a default is exported, but uses some kind of simpler test to drop out early before actually evaluating the file where it would find out there was indeed a default export.

I'm interested to see that you say yours is working with target `web`, I'll check that out.

**Comment by MStoykov** [comment]
Goja *does* actually run the code. It does *not* just check for some string match or some other thing. 
In particular (too much detail probably) `export default whatever` will be transpiled (by babel) to `exports.default = whatever` and the line you've found `exports.Get("default")` is the actual getting of the property "default" of that `exports`. 
So your code is *not* exporting a default function ... Maybe it does in some strange way .. or if we call it in some specific way (I am not familiar with UMD), but not if it's just executed. 

Again you should be using `commonjs`(most likely). And using `web` will help with polyfilling nodejs std lib if any is used. 

The error you are mentioning in your "edit" seems to be npm being ... npm :) try to run a stable version of npm or something ... I generally use docker as not to spill node modules everywhere and for reproducibility.

**Comment by johnrom** [comment]
Interestingly I thought I tried every target listed in the [webpack docs](https://webpack.js.org/configuration/output/#outputlibrarytarget) (including `commonjs`, `commonjs2`, and `commonjs-module`). Some of them worked with just a default function, but wouldn't work with `default` _and_ `setup()` exported. I'll circle back again after I finish the thing I needed to load test in the first place. I'm perfectly fine if this is just a matter of adding documentation. I did try _everything_ I could think of to get both a default export and a setup function working.

**Comment by MStoykov** [comment]
@johnrom , how has it gone ? I just tested it and it worked for me inside of a `circleci/node:11`
 docker container where the versions are : 
```
$ npm version
{ 'k6-es6': '1.0.0',
  npm: '6.7.0',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '34.0',
  http_parser: '2.8.0',
  icu: '63.1',
  llhttp: '1.1.1',
  modules: '67',
  napi: '4',
  nghttp2: '1.34.0',
  node: '11.13.0',
  openssl: '1.1.1b',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.27.0',
  v8: '7.0.276.38-node.18',
  zlib: '1.2.11' }
```

**Comment by johnrom** [comment]
I probably won't be able to circle back to this until next week, as I have to make performance tweaks to make on the target. I'm thinking it's likely it doesn't work with Node LTS 8, which is fine if that's the case.

**Comment by ppcano** [comment]
There are now two templates to generate a project using ES6 features or TypeScript in your k6 scripts.

https://github.com/k6io/template-es6
https://github.com/k6io/template-typescript

The issue looks inactive. Can it be closed? @MStoykov

**Comment by MStoykov** [comment]
I think so as well

**Comment by johnrom** [comment]
All good here. I continued using the file which imported and re-exported everything, and sadly never got around to trying the alternatives.

**Comment by baralraj** [comment]
I am trying use `fs` module and tried everything but the `fs` is coming empty. I used [this k6-es6 template](https://github.com/grafana/k6-template-es6) and the additional changes I did in webpack.config.js as 

```
node: {
    fs: "empty",
  },
```

I have several test file in my directory and I need to read them one by one and post as a body. What could be the solution for me?

**Comment by mstoykov** [comment]
Hi @baralraj, This likely is better of as a question in the [community forum](https://community.k6.io/) instead of on a 2 year old issue, that isn't even that related ;). 

I doubt you will be able to use the nodejs `fs` module. As I mention above k6 is not nodejs library or using it in any way. The `fs` module gives unprecedented access to the host filesystem and for security (and distribution reason) k6 is unlikely to ever get all that much of them implemented. And even if it did AFAIK the `fs` package doesn't get polyfilled so you will need to use the custom package from k6 - w/e it will be called.

But it does have [`open`](https://k6.io/docs/javascript-api/init-context/open/), so for your case you can put all of the names/paths of the files in an array, iterate with a for and open them to get what you need and then use them in the bodies.

How well that will work is a different question. Some thoughts on a similar question can be found [here](https://community.k6.io/t/unique-file-upload-per-iteration/4115/3?u=mstoykov) with more explanations on some of the topics and more involved ways to fix this.
