### ISSUE TITLE
Quiet flag to suppress stdout

### ISSUE THREAD

**Issue by martinfijal** [loadimpact/k6#117]
I'd like a --quiet flag to suppress the default output printed on stdout when running a test.

**Comment by uppfinnarn** [comment]
Do you mean the progress bar and all that, or the post-test summary as well?

(all logging is to stderr, if you wanna separate that out.)

**Comment by martinfijal** [comment]
Mainly the progress bar since it's not needed when doing CI or run k6 through shell scripts.

**Comment by jberryman** [comment]
Is `--quiet` just undocumented? Is there some way to set it as part of the test configuration options?

**Comment by na--** [comment]
@jberryman, sorry, we recently realized we lack documentation for that option and we plan to fix this soon: https://github.com/k6io/docs/issues/315

In short, `--quiet` can't be configured from the exported script `options`, since its value has to be known before k6 even reads the script. Currently, it can only be configured via the CLI flag.
