### ISSUE TITLE
k6 should not panic when os.UserConfigDir returns an error

### ISSUE THREAD

**Issue by cuonglm** [loadimpact/k6#1176]
In #1162, we replaced `configdir` library with go1.13 [os.UserConfigDir](https://golang.org/pkg/os/#UserConfigDir), and panic if it returns an error.

That's a backward in-compatible change, and can affect user experience.

In case `os.UserConfigDir` returns an error, what should we must do?

**Comment by na--** [comment]
I think we should default to `config.json` as the default config file path, if we can't determine the proper configdir. No path, just `config.json`, so k6 will try to read/write that file in the current working directory. Unfortunately, that would also be a breaking change (but much better than panicking) :disappointed:

It's a breaking change, because when I currently `unset HOME` and run `k6 run -h`, the default config path value k6 v0.25.1 uses is `.config/loadimpact/k6/config.json`

**Comment by MStoykov** [comment]
Technically we can, make it backward compatible :). Although, I think I would prefer if it's `config.json` if there is not `$HOME`, as I don't think people would like to make this directory structure to get the config file to work ... 
I don't know how common it is to not have `HOME` set and than how many people have decided to use the current default in that case, but I doubt there are many, as it seems strange and I doubt people would've figured it out either way. I guess if they needed config in this situation they would've just used the cli flag

**Comment by na--** [comment]
We forgot to mention that a warning message if we can't find the configdir makes some sense, to let users know that k6 is actually trying to use that folder.
