### ISSUE TITLE
POST request with multipart/form-data missing in HAR conversion

### ISSUE THREAD

**Issue by Sam7** [loadimpact/k6#1227]
I was recording a session in Chrome and converting the HAR to JS using K6 and found that one crucial request was missing from my script I simplified it down for you to test:
https://gist.github.com/Sam7/a267e875d77981254fd2a206070c58cd

The request just get's completely ignored and is not showing up on the JS file file 

This is the command I used:
`k6 convert .\xxx.zoo.org.au_simplified.har -O xxx.zoo.org.au_simplified.js`
Even verbose doesn't give me any more insight about what's going wrong.

Thanks.

**Comment by MStoykov** [comment]
The internal to k6 har converter is discontinued, predominantly because it's not the best code and because the scope is somewhat outside of what k6 should be doing. There is an [external project](https://github.com/loadimpact/har-to-k6) which probably handles this (and a lot of other things) a lot better. 

The code in question that breaks this is [here](https://github.com/loadimpact/k6/blob/1922251e668d6b5ecd05adb01c3829d3a6efed4d/converter/har/converter.go#L134-L137). But we do actually intend on starting to tell people to stop using the k6 internal converter (#1124) . So at best we are going to add a warning that the request will be skipped ... which should've been there from the start ... :man_facepalming: 

I just tested with the [har-to-k6](https://github.com/loadimpact/har-to-k6) tool and I am getting an error but I don't know if the tool also doesn't support multipart/form-data (which works in some amounts in k6) or is your script too simplified. When you try it and if it doesn't work for the whole script as well please report an issue there. 

```shell
$ npx har-to-k6 xxx.zoo.org.au_simplified.har  -o output.tar
Converting 'xxx.zoo.org.au_simplified.har'
Error converting archive:
Post data conflict (0): specify 1 of params or text
$
```

**Comment by Sam7** [comment]
Great. thanks I'll give that a whirl.

**Comment by na--** [comment]
Closing this, since even if we're discontinuing the k6 built-in HAR converter, the bug was already described in https://github.com/loadimpact/k6/issues/747
