### ISSUE TITLE
k6-es6 example not working

### ISSUE THREAD

**Issue by joostmeijles** [loadimpact/k6#1282]
The JS compatibility mode documentation (https://docs.k6.io/docs/javascript-compatibility-mode), points to an example that does not work: https://github.com/MStoykov/k6-es6

Running the k6-es6 example results in:
```
ERRO[0001] TypeError: util.promisify requires a true ES5 environment at file:///C:/Repos/k6-es6/build/app.bundle.js:8:273234(42)
```

**Comment by MStoykov** [comment]
@joostmeijles can you provide the script that doesn't work? 
Also this is probably better for the [k6-es6](https://github.com/MStoykov/k6-es6) repo as it is the one that is trying to do the job of translating ES6+ to ES5.1 that k6 can then run. But lets continue here for now :)

**Comment by joostmeijles** [comment]
@MStoykov I followed the steps from the README:
```
npm install
npm run-script webpack
k6 run build/app.bundle.js
```

Using Node v10.16.2 and K6 v0.26.0 (dev build, go1.13, windows/amd64) on Windows 10.

**Comment by MStoykov** [comment]
I was mostly asking for the script that didn't work (or better smaller example that showcases it). 
But looking at this again [util.promisify](https://nodejs.org/dist/latest-v8.x/docs/api/util.html#util_util_promisify_original) is about promises and async stuff and k6 [currently doesn't have an event loop](https://github.com/loadimpact/k6/issues/882), so it's totally normal that running through k6-es6 won't help at all. 

Does the script work before you run it through k6-es6, because that will be an interesting problem as well? But in general, if it doesn't work without running it through k6-es6 it is very doubtful it will after. 

Also as it is mentioned k6-es6 is a proof-of-concept. I would really prefer it if we can extend it and make it work for everything, but it won't work for anything that k6 conceptually doesn't support

**Comment by joostmeijles** [comment]
The problem is that the example uses `xml2js`. 

Simple fix would be to remove that and update the docs with the event loop limitations.

**Comment by simskij** [comment]
Thank you for your report! I will have a look at this as soon as I get some time on my hands. 🙏🏼

**Comment by MStoykov** [comment]
I did try to make it work, as supposedly it should be able to,but all my tries were in vain. 

Fortunately @simskij who has some knowledge about how webpack works will have more success.

**Comment by simskij** [comment]
Hey,

I've been looking at this for the last couple of days and, unfortunately, it seems like we currently are unable to run xml2js, and cheerio for that matter, in `--compatibility-mode=base` due to limits in how webpack polyfills dependencies.

A workaround for this until goja gains es6 support (which is [currently on its way](https://github.com/dop251/goja/tree/es6)), is to:

1. Add `@babel/polyfill`
2. Modify `.babelrc` to use `entry` instead of `usage` as it's `useBuiltIns` option.
3. Add `import '@babel/polyfill'` to the top of your script file.

Hope this solves your issue while we await the goja es6 branch!

Simme

**Comment by simskij** [comment]
For future reference:

All of these tests have been run with `--vus 100 --paused`.

| Base | Config | Memory Consumption | Comment |
| - | - | - | - |
| ✅ | `@babel/preset-env` and `useBuiltIns: 'usage'` | N/A | Errors out |
| ✅ | `@babel/preset-env`, `@babel-polyfill` and `useBuiltIns: 'entry'` | 6.3GB | Requires import in test script |
| ❌ | `@babel/preset-env` and `useBuiltIns: 'usage'` | 6.3GB | |
| ❌ | `@babel/preset-env`, `@babel-polyfill` and `useBuiltIns: 'entry'` | 6.5GB | Requires import in test script|
| ✅ | `@babel/preset-env` and `useBuiltIns: 'usage'` | 234mb | without `cheerio` and `xml2js``

**Comment by simskij** [comment]
I've [updated the docs](https://github.com/loadimpact/k6-docs/commit/79b6103a27dcc9dd7bd47f2217c3f105f5f10e8f) as suggested. Closing this issue for now.

Thank you for bringing this to our attention!
