### ISSUE TITLE
Testing each group with different throughput

### ISSUE THREAD

**Issue by anaguib87** [loadimpact/k6#1288]
I have an API which contains 6 endpoints. My target is to reach 10x throughput for all endpoints, but the issue is that each endpoint has its own target, as follows:

api/Get > current rpm 2k > targeted rpm is 20k
api/GetMany > current rpm 800 > targeted rpm 8k
Because it doesn’t make any sense to put all endpoints/groups in one single file/script and all gets the same throughput, I had to separate them each in a separate file.

What I wanna do is having all groups in one script, but all runs and stops based on specific stage

**Comment by na--** [comment]
There's no need to post the same thing across the [community forum](https://community.k6.io/t/testing-each-group-with-different-throughput/347), [StackOverflow](https://stackoverflow.com/questions/59435197/testing-k6-groups-with-separate-throughput/), and here... :wink: Since this is more of a question, I'm closing this issue in favor of the community forum post. We can discuss the topic there and if a feature request or an improvement idea for #1007 emerges in that discussion, I'll create a new issue for it.
