### ISSUE TITLE
K6 slows down when testing nginx with loadbalancing

### ISSUE THREAD

**Issue by klimashkin** [loadimpact/k6#1291]
Hi! That is probably not a K6 issue, but I couldn't find a solution.
I have 4 NodeJS servers running on ports 9001-9004 which just respond with Hello World:
```js
const port = process.env.PORT || 9001;

require('http').createServer((req, res) => {
  res.end('Hello World!');
}).listen(port, err => {
  if (err) {
    console.log('something bad happened', err);
  }
  console.log(`Pure http server is listening on ${port}`);
});
```

Then I have a nginx server with simple round-robin load balancing from port 9000 between those nodes:
```
worker_processes  4;
error_log  logs/error.log warn;
pid        logs/nginx.pid;
worker_rlimit_nofile 16384;

events {
    worker_connections 16384;
    multi_accept on;
}

http {
    upstream myapp1 {
        server 127.0.0.1:9001;
        server 127.0.0.1:9002;
        server 127.0.0.1:9003;
        server 127.0.0.1:9004;
    }

    server {
        listen 9000;

        location / {
            proxy_pass http://myapp1;
        }
    }
}
```

And a simple K6 config in benchmark.js:
```js
import http from 'k6/http';
import {check} from 'k6';

export default function () {
  const response = http.get('http://127.0.0.1:9000');

  check(response, {
    'status was 200': r => r.status === 200,
  });
}
```

And if I run `k6 run --vus 100 -d 30s benchmark.js` then for some reason in Activity Monitor I see CPU load on K6 process and on nginx/nodejs processes only for the first 5-6 seconds, then CPU drops to zero and nothing happens with the final result that K6 shows around 500 req/sec.

If in benchmark I change 9000 to say 9001 (to hit one of the nodejs directly) then I get 30k/sec with constant CPU load.

Not sure what is happening, no errors or warning shown on any of the processes. Hoping to get some help or hint from the community.
Platform: MacOS Catalina

**Comment by MStoykov** [comment]
Hi, sorry for the slow response ... but holidays :D. 

This doesn't look like a k6 bug/issue and it probably was going to be better for the [community forum](community.k6.io/). 

I did [create a repo](https://github.com/MStoykov/issue-1291) to test it out using docker-compose and the primary reason why your setup will have problems is that it will not be reusing connections from Nginx to the nodejs instances. Also by default Nginx closes keep-alive connections after 100 requests are done through them, which also will make it look much worse with Nginx instead of without it.
The **really** important parts are:
```
            proxy_http_version 1.1;
            proxy_set_header Connection "";
```
In order for keep-alive connections to the upstream to be used at all. 


```
        keepalive_requests 10000000;
``` 
To use a keep-alive connection for much more than just 100 requests


 `access_log` also had a performance penalty, which is why I dropped it.

In my testing nodejs doesn't hit 100% CPU, but k6 eats all the CPU available making requests, which means that I was still getting worse RPS with Nginx as a load balancer((7-7.5k RPS) instead of just hitting 1 nodejs instance(10k RPS) on my laptop.

I would consider this reasonable given the fact that the load-balancing isn't helping at all, in this case, it just adds additional work. 
I am going to try and run it on my server machine (which is currently out) on which I will be able to (hopefully) get 100% CPU usage for the nodejs instance. 

Also, you should probably look at [this article](https://docs.k6.io/docs/fine-tuning-your-os) as if you haven't increased your open files limit it will also be a problem, especially as your Nginx which was not reusing connections but instead was just making more and more.
Although in this case, k6 would've logged some amounts of errors and Nginx has error_log which probably would've had something as well. Did you have error messages in the k6 output?  

I am closing this as this is not an issue with k6 ... again this is much better for the [community forum](community.k6.io) where more people are going to look at it (probably) and might be able to help you better as I have never used MacOS (at all) and my Nginx skills are rusty :)

**Comment by klimashkin** [comment]
Thank you @MStoykov for the investigation! For some reason I had missed the fact that there is a community forum..

Increasing `keepalive_requests` helps indeed! Four processes of nodejs in this case behind the four processes of nginx gives me around the same rate (30k) as one nodejs instance directly. At the same time pm2 with cluster mode instead of nginx gives me 40k. But seems like it's because I simply run out of CPU processes locally when adding nginx.

Will be investigating further with separate server.
