### ISSUE TITLE
Spinner during VU init?

### ISSUE THREAD

**Issue by ragnarlonn** [loadimpact/k6#1324]
VU init at the start of a test can take many seconds to complete, during which a new user may think k6 has failed/frozen as there is no feedback. 

## Feature Description
I propose using a simple ASCII spinner ("|", "/", "-", "\") to show the user that work is being done.

**Comment by na--** [comment]
This has already been mostly solved in #1007, we have a progress bar that measures VU initialization progress there. And we initialize VUs concurrently instead of sequentially, so it usually happens way faster :smile: 

@imiric is actively working on prettifying the progressbars for that PR even more right now https://github.com/loadimpact/k6/pull/1310! Take a look at how it is like when you initialize and run different tests with the code from that branch: [![asciicast](https://asciinema.org/a/ZA4O1YJcj1mLnAfNE96ls21Rg.svg)](https://asciinema.org/a/ZA4O1YJcj1mLnAfNE96ls21Rg)

(ignore the `context cancelled` errors, we know how to solve that thorny issue: https://github.com/loadimpact/k6/issues/1283)

**Comment by na--** [comment]
That said, we actually plan to add a spinner, only it will probably be when an executor is running: https://github.com/loadimpact/k6/pull/1310#discussion_r372915532

**Comment by na--** [comment]
@ragnarlonn, closing this for now, but feel free to re-open, or comment in the other issues/PRs that I linked to, if you think something could be further improved :slightly_smiling_face:
