### ISSUE TITLE
Millsecond delays

### ISSUE THREAD

**Issue by mschwartz** [loadimpact/k6#1431]
I see no blessed method for implementing delays shorter than 1 second.

## Feature Description
I tried sleep(.5) and it does not sleep for .5 seconds, for example.

Without setTimout and setInterval and async/await kinds of functionality, the only way I figured out was to do something like this:

```
const when = Date.now() + 200; // 200 ms
while (Date.now() < when);

```

Is this to be avoided?

My use case is a WWW/browser based game where clicking as fast as you can generates a couple of patch requests to the game/http server.  Batching the requests as HAR seems to (on .5 second intervals) is not fine enough to accurately test the application server.

What we really want to do is simulate a click (the 2 requests), wait some random time between 175ms and 250ms and repeat.

## Suggested Solution (optional)
The sleep method could take fractional seconds.  Or a usleep(milliseconds) method.

**Comment by MStoykov** [comment]
sleep seems to work perfectly fine with fractional seconds for me 
```javascript
var sleep = require("k6").sleep;

function sleepAndPrint(t) {
    var start = Date.now();
    sleep(t);
    console.log(t, Date.now() - start);
}

exports.default = function () {
    sleepAndPrint(0.1);
    sleepAndPrint(0.1);
    sleepAndPrint(0.1);
    sleepAndPrint(0.5);
    sleepAndPrint(0.5);
    sleepAndPrint(0.001);
    sleepAndPrint(0.001);
    sleepAndPrint(0.001);
}
```

When ran with v0.26.2 will print:
```
INFO[0000] 0.1                                           0=100
INFO[0000] 0.1                                           0=101
INFO[0000] 0.1                                           0=100
INFO[0000] 0.5                                           0=500
INFO[0001] 0.5                                           0=500
INFO[0001] 0.001                                         0=1
INFO[0001] 0.001                                         0=1
INFO[0001] 0.001                                         0=1
```
I did test it a lot of times and while there will be +/- 1millisecond on one of them every time I still think this is close enough.

**Comment by mschwartz** [comment]
Using the docker image, I observed:

```
console.log(Date.now());
sleep(.175);
console.log(Date.now());
```

and no change in the value printed before/after.

I do think 1ms is close enough.  Is the while() loop in the opening comment acceptable?

**Comment by MStoykov** [comment]
> and no change in the value printed before/after.
This seems like something is wrong - I just tested it and it does work perfectly within docker as well and ... well, it should :D. 

Can you provide us with what OS you are running on and which version you are using (although I don't think we've touched this since forever), as this seems like a buggy behavior... although I expect it is docker to blame as we don't do anything interesting in this case ... :( 

> I do think 1ms is close enough. Is the while() loop in the opening comment acceptable?

acceptable for what? performance testing - unlikely you are likely to eat all the CPU of the load generator machine doing the loop. I guess if you have more Cores then VUs it will work ... okayish, but I wouldn't call that a performance test.  You are free to try and see how it will go, but while it will probably "work" it will be mostly not okay for whatever you intend to use it for. Also if sleep doesn't work as expected in your docker why do you think `Date.now()` will?

> Also, the documentation could be clearer. Sleep(seconds) implies an integer number of seconds, not particularly a fractional number.

I am open for suggestions -  you can use the "suggest edits" on the [page](https://k6.io/docs/javascript-api/k6/sleep-t) to get you to the github repo page of the documentation in question, from where you can edit the file and make us a PR ;)

**Comment by mschwartz** [comment]
Date.now() does work in the container.  I would obviously prefer to use sleep().

The host is Arch Linux running Docker.

I am willing to revisit my testing and see if I somehow had a bug in my code.
