### ISSUE TITLE
Don't build docker containers if we aren't gonna push them

### ISSUE THREAD

**Issue by MStoykov** [loadimpact/k6#1476]
I doubt we will find anything by constantly building them. But we currently do. 
This adds another 1m and 30s to each build for no reason IMO. 

This can probably wait for us to move to github actions, but maybe it will be fairly easy using the `filters` ?

**Comment by na--** [comment]
I disagree with the premise of the issue entirely, for historical reasons, github actions or no :smile: I want to always build the docker images, even if we don't push them. This would prevent the situation, which has happened in the past, of `git tag`-ing a release and then having an error in the `Dockerfile`, or some stupid Alpine change, or something else, that basically makes it so that you have to make a new release to fix it.

I'd honestly want to go completely in the other direction to what you propose - build all packages all the time, including OS packages and installers, and only push the ones that are for tagged releases. Or maybe not all of the time, but for sure on every `master` commit... So that actual releases become not very special from a CI perspective.

**Comment by na--** [comment]
Also, the `build-docker-images` step is not actually required for a PR to be merged, so it's not a blocker for normal everyday work.

**Comment by MStoykov** [comment]
Then maybe move it only for it getting build on `master`?

**Comment by na--** [comment]
Not completely opposed to that, but still seems like a downgrade. For example, you might want to make changes to the Dockerfile or adjacent things (like changing Go versions or messing around with modules, for example)...

Ideally, the `docker build` step, and other package builds, should happen at the same time as the testing and linting. That way we won't have to wait for them, while still getting the benefit of knowing that packaging isn't broken. And the pushing of the tagged releases should be its own separate step that is triggered only on git tags, and only if all previous steps were successful and error-free. And these `push-*` steps should reuse whatever binary results the previous `build-*` steps generated. 

If we do this, and I think it can be done with github actions somewhat easily (https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts), then all of the builds can happen for pretty much every commit in every PR...
