### ISSUE TITLE
URL-grouping

### ISSUE THREAD

**Issue by caalle** [loadimpact/k6#148]
Issue to keep track of discussion about URL-grouping.

Would like some way of grouping URLs together when they consist of dynamic segments. 

Solutions that have been up for discussion:

* Passing name/id/whatever when doing request:
    `http.get(random_url, {name: "my-url-group-name"})`
* Automatically storing original string template(not sure if possible?):
    ```http.get(`http://example.com?id=${random_id}`)```
* ... other automatic way with regexp?

**Comment by micsjo** [comment]
Tagging preferable I think - then you get the individual results _and_ you can also group by tags.

Why would you want this inside k6? And not in the analysis part? As much raw data as possible and then working with the data in the analysis.

**Comment by caalle** [comment]
Not saying that the amount of raw data should be reduced. Only that it would be nice if it was possible to guide the user into adding a predefined tag that we can use to determine if the urls are equal or not.

It feels more intuitive to let the person that is writing the test decide if the urls are equal or not than having a regexp input field in the web app that is applied to all urls in the test run.

I think @ppcano or @robingustafsson might have more input to this as well.

**Comment by micsjo** [comment]
There are other ways than letting people type regexp in the webapp. More user friendly ways such as just have a slider right->left. Most probably other ways as well. But the implementation itself is not the point.

The person who writes the test will most probably not at the time of writing even consider if URLs should be grouped or not but will add in later iterations of refining the tests.

But tagging seems (to me) to be the best way to do this inside k6? It adds information that we can do stuff with (such as grouping URLs)  rather than removing information that we can't find once done.

There are use cases when the root cause of a problem actually is data dependent and we need separation of individual URLs to find that.

Consider this

http://myserver/direction?goleft=true
http://myserver/direction?goright=true

goleft responds in 100 ms and goright in 10 s. 

You will hide this if you group them and falsely assume direction is slow but as long as we keep the original data as well we can drill down at a later stage in analysis.

So: tagging seems to make sense as the proposed solution as long as we don't discard the rest of the data.

**Comment by ppcano** [comment]
@micsjo The term `tagging` has confused me with the `tags` API.

```
http.get(`${baseURL}/${username}/login`, {
			tags: {'kind': 'js' }
})
```


I am also for the `URL tagging/naming` API in a similar way than [Locus](http://docs.locust.io/en/latest/writing-a-locustfile.html#grouping-requests-to-urls-with-dynamic-parameters)

```
http.get(`${baseURL}/${username}/login`, {
			tags: {'kind': 'js' },
                        name: 'login'
})
```

I raise the idea if k6 or the UI should auto-generate the URL name by default per request statement.

- If `name` tag is present,  use `name` value as URL name.

- If `name` tag is not present and a request statement originates always the same URL value, use it as URL name.

- If `name` tag is not present and a request statement originates different URL values, auto-generate an URL name ( URL 1, URL 2...). Additionally, the UI should link to the `URL naming` feature.

_Note: I am not concerned about the internal implementation (k6 or UI), but what information will be presented to the user._


cc @robingustafsson @caalle @uppfinnarn

**Comment by uppfinnarn** [comment]
What about something along the lines of:

```js
import { u } from "k6";
import http from "k6/http";

export default function() {
    let id = 1234;
    http.get(u`http://example.com/things/${id}/`);
}
```

The `u` function would return here object of `{ url: "http://example.com/things/1234", template: "http://example.com/things/${}/" }` or something of the sort, and when `http.request()` gets one of these objects, it adds a `template` tag to the emitted metrics.

**Comment by caalle** [comment]
Discussed offline to go with ```http.get(url`http://example.com/things/${id}/`);``` adding a tag called something like `name` with the template `http://example.com/things/${}/`.

If no `name` tag i provided we'll fallback on adding `<group>:<request-sequence-number>`.

User can override both b setting the `name` tag manually.

**Comment by robingustafsson** [comment]
@liclac @caalle What is the status of this?

**Comment by ppcano** [comment]
@caalle @robingustafsson  status? 

I don't think the current Insights view working without this addition.

**Comment by caalle** [comment]
From the Insights perspective this is handled. If you add a tag named `name` to the Requests they will be grouped together. @ppcano @robingustafsson 

```javascript
// Setting a `name` tag will group these two requests together in Insights
const firstResponse = http.get('http://some-url.com', { tags: { name: "GET Request" } })
const secondResponse = http.get('http://other-url.com', { tags: { name: "GET Request" } })
```

**Comment by ppcano** [comment]
ok, I tested and it works. It's pending to automatically tag if name tag is not present.

> If no name tag i provided we'll fallback on adding <group>:<request-sequence-number>.

I don't find this pending issue to be urgent. I will manage to create some documentation about how to group URLs.

**Comment by liclac** [comment]
Here we go; for ease of use in eg. Grafana, the `name` tag defaults to the same value as the `url` tag, and can be overridden like usual with the `tags` option.

```js
// name="http://example.com/"
http.get("http://example.com/")

// name="http://example.com/posts/1", name="http://example.com/posts/2", etc.
for (var id = 1; id <= 100; id++) {
  http.get(`http://example.com/posts/${id}`)
}

// name="http://example.com/posts/${}/", both equivalent
http.get(`http://example.com/posts/${id}`, { tags: { name: "http://example.com/posts/${}/" }})
http.get(http.url`http://example.com/posts/${id}/`)
```

**Comment by ppcano** [comment]
@liclac Thanks, I have tested it and it works well. Some thoughts:

The original feature request had the intention to cover 2 cases:

1) Passing name/id/whatever when doing request:
    `http.get(random_url, {name: "my-url-group-name"})`

2) Automatically storing original string template(not sure if possible?):
     ```http.get(`http://example.com?id=${random_id}`)```

The idea of the use case 2 is that k6 was able to automatically identify URL based on request statements because users will likely write statements like:

   
     http.get(`http://example.com?id=${random_id}`)
     http.get("http://example.com?id="+value)
    

This was the reason we ended up with:

> If no name tag is provided we'll fallback on adding "group:request-sequence-number"

Now, I have seen the commit and thought again about the feature request; it adds a lot of complexity and it is unreliable because request statement position could change depending on conditional statements and cloud execution environment amongst other factors. Therefore, I have changed my mind and I don't think k6 should solve the use case 2.

The `http.url` wrapper class does not solve the use case 2; it is another syntax to configure the name tag. I will be adding it to the doc soon.

**Comment by liclac** [comment]
It's setting the `name` tag based on the template, but unfortunately, we can't actually see the original expression for the placeholders, only the result and position in the string...

**Comment by ppcano** [comment]
@liclac 

Can you tag or "track" the script line number? The script line number with the group ID could be useful to perform automatically aggregations.

**Comment by liclac** [comment]
Unfortunately not, I can get the line number from exceptions, but that's it...

Isn't group + URL + name unique enough?

**Comment by ppcano** [comment]
IMO, Yes, it is. I tried to give the explanation above so others can also read the status/discussion. 
Let's close the discussion. Thanks for the help.
