### ISSUE TITLE
Too many i/o timeout error

### ISSUE THREAD

**Issue by guawazi-glitch** [loadimpact/k6#1494]
## Environment

- k6 version: k6-v0.26.2-linux64
- OS and version: linux version 3.10.0-514.el7.x86__64  red hat 4.8.5 20150623
- Docker version and image, if applicable:

## Expected Behavior

Should work well

## Actual Behavior

The terminal output many error like :
WARN[0182]  error="Get http://xxx.xxx.xxx.xxx:port  dial tcp xxx.xxx.xxx.xxx:port i/o timeout

## Steps to Reproduce the Problem

The command is
./k6 run --vus=7000 --duration=3m --no-thresholds --compatibility-mode=base --discard-response-bodies test.en5.js

I want to generate a large loading . When the vus is 5000, everything is ok. But if the vus becomes 7000  there are many i/o timeout error occurred. Any suggestion for this issue? thanks.

**Comment by MStoykov** [comment]
Hi @guawazi-glitch this very likely either the load generator or the target system getting overwhelmed. 
There is [this](https://k6.io/docs/testing-guides/running-large-tests) guide on how to run large tests which can help you with some technics as well as with what errors mean what. 
I will close this isseu. 
If it turns out that both systems are not overloaded and there is enough bandwidth between them, feel free to reopen it with more information.

**Comment by guawazi-glitch** [comment]
@MStoykov  Hi, I've read the large tests article and followed the instruction in this article. But I've tested in my own server.  I increased the vus from 1000 to 3000, and duration is always 3m. The http_reqs always is between 15000 - 17000. I want to arrive RPS 20000, what should I do to arrive 20000?

**Comment by MStoykov** [comment]
@guawazi-glitch this to me seems like this is the maximum your setup can support then ... more VUs won't help you if your system under test can't make more responses and it won't help if your bandwidth bounded ...
