### ISSUE TITLE
tlsCipherSuites and tlsVersion aren't properly marshalled in archives 

### ISSUE THREAD

**Issue by na--** [loadimpact/k6#1560]
If we have a script like this:
```
export let options = {
    tlsCipherSuites: [
        "TLS_RSA_WITH_RC4_128_SHA",
        "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
    ],
    tlsVersion: {
        min: "tls1.0",
        max: "tls1.2"
    }
};
```
and we archive it with `k6 archive`, we'd get something like this for the options :sob: 
```
    "tlsCipherSuites": [
      5,
      49162
    ],
    "tlsVersion": {
      "min": "",
      "max": ""
    },
```

Another way to test it:
```
$ k6 inspect 'github.com/loadimpact/k6/samples/tlsconfig.js' | jq '.tlsCipherSuites,.tlsVersion' 
[
  5,
  156
]
{
  "min": "ssl3.0",
  "max": "tls1.2"
}

$ k6 archive 'github.com/loadimpact/k6/samples/tlsconfig.js'  && (tar xfO archive.tar metadata.json | jq '.options.tlsCipherSuites,.options.tlsVersion') 
[
  5,
  156
]
{
  "min": "",
  "max": ""
}
```

notice how `tlsVersion` was reasonably ok with `k6 inspect`, there are probably 2 different bugs here...

**Comment by keithfitzgerald** [comment]
I ran into a similar problem trying to set the TLS min/max version in js:

```
export let options = {
    tlsVersion: {
        min: "tls1.1",
        max: "tls1.2"
    }
};
```

I tracked the problem down to `readEnvConfig()` in `cmd/config.go`. When `envconfig` scans `lib/options.go` it picks up the min/max int fields and sets them to zero. When that config is then applied over the the runner config it wipes out the values.  From `cmd/config.go`:

```	envConf, err := readEnvConfig()
	if err != nil {
		return conf, err
	}

	conf = cliConf.Apply(fileConf)
	if runner != nil {
		conf = conf.Apply(Config{Options: runner.GetOptions()})
	}
	conf = conf.Apply(envConf).Apply(cliConf) <- This apply clobbers the runner's options
```

The `Apply` function on `Options` expects the `TLSVersion` field to be `nil` otherwise it will overwrite the values. 

Since setting the TLS version is not supported as an env var (at least according to the docs: https://k6.io/docs/using-k6/options#tls-version) a fix that worked for me was to mark those fields as ignored.

```diff --git a/lib/options.go b/lib/options.go
index 2f51d61a..6f32f1bc 100644
--- a/lib/options.go
+++ b/lib/options.go
@@ -69,8 +69,8 @@ func (v *TLSVersion) UnmarshalJSON(data []byte) error {
 
 // Fields for TLSVersions. Unmarshalling hack.
 type TLSVersionsFields struct {
-       Min TLSVersion `json:"min"` // Minimum allowed version, 0 = any.
-       Max TLSVersion `json:"max"` // Maximum allowed version, 0 = any.
+       Min TLSVersion `json:"min" ignored:"true"` // Minimum allowed version, 0 = any.
+       Max TLSVersion `json:"max" ignored:"true"` // Maximum allowed version, 0 = any.
 }
 
 // Describes a set (min/max) of TLS versions.
@@ -235,7 +235,7 @@ type Options struct {
 
        // Specify TLS versions and cipher suites, and present client certificates.
        TLSCipherSuites *TLSCipherSuites `json:"tlsCipherSuites" envconfig:"K6_TLS_CIPHER_SUITES"`
-       TLSVersion      *TLSVersions     `json:"tlsVersion" envconfig:"K6_TLS_VERSION"`
+       TLSVersion      *TLSVersions     `json:"tlsVersion" ignored:"true"`
        TLSAuth         []*TLSAuth       `json:"tlsAuth" envconfig:"K6_TLSAUTH"`
 
        // Throw warnings (eg. failed HTTP requests) as errors instead of simply logging them.```

**Comment by berndhartzer** [comment]
I was having a look at this and I think the `inspect` command issue can be fixed by correctly implementing the `MarshalJSON()` function for the `TLSCipherSuites` type (in `lib/options.go`).

From what I can see as well, @keithfitzgerald 's suggestion in the comment above will fix the `archive` command, is it correct that we can remove the `envconfig` tag from `TLSVersion`? As pointed out, its not supported in the docs.

**Comment by na--** [comment]
Ah, so this is essentially another instance of this envconfig issue? https://github.com/kelseyhightower/envconfig/issues/113 :disappointed: Yet another reason to get rid of that library (https://github.com/loadimpact/k6/issues/671, https://github.com/loadimpact/k6/issues/1257) altogether... 

But yes, for now telling it to ignore these fields seems like an OK quick fix. We can always add support for configuring them via environment variables when we refactor the configuration to use some other library (or, more likely, roll our own, given how easy it can be).

**Comment by berndhartzer** [comment]
Cool. I think I've got a fix for this I can make a PR for. Just wanted to check with @keithfitzgerald if you wanted to make your own PR for the `archive` command fix you proposed? I'm happy to submit my PR for fixing `inspect`, and can also include the fix for `archive` if you're not planning to do your own PR, just let me know!
