### ISSUE TITLE
Explain how to add a Go package to k6

### ISSUE THREAD

**Issue by mardukbp** [loadimpact/k6#1595]
## Feature Description

k6 comes with some Go packages, but it may happen that one needs a Go package that is not included.
In my case I needed to generate a CMAC and I had to learn by myself how to do it. This information 
should be readily available in the documentation, thus saving users a lot of time and making k6 even
more awesome!

## Suggested Solution

A Go package template and instructions for adding it to k6 are provided in my [k6gopackage](https://github.com/mardukbp/k6gopackage) repository. 
It should be a good starting point for writing the missing documentation.

**Comment by na--** [comment]
Thanks for the suggestion and example repository! In general, we don't think users modifying k6 itself is the best possible UX. While, as you've demonstrated, it's not hard to do, then you'd need to port your changes to every future k6 version.

To get most of the same benefits, but do it in an easier to maintain way, we plan to add plugin support in k6 v0.28.0. You can find more information in the issue (https://github.com/loadimpact/k6/issues/1353) and PR (https://github.com/loadimpact/k6/pull/1396). The "JS plugins", which are the only plugin type we'll support initially, look very similar to what I'm seeing in your repo, but wouldn't require users to modify the k6 source itself. They'd still require some advanced knowledge (or future plugin repository and management infrastructure on our side), since they may need to be compiled with the same Go version as k6. The also have some limitations, e.g. they can only work on Windows through Docker (and maybe WSL), because of [Go specifics](https://golang.org/pkg/plugin/). But, even with both of these considerations, it's likely still better than modifying k6 and having to support a fork, for most use cases. We also plan to extend plugin support in the future to other k6 components, like outputs outputs and executor types, at the very least...

I added a docs issue to document the plugins here when they are merged (https://github.com/loadimpact/k6-docs/issues/85), so I'll close this one. Feel free to comment in any of the issues I linked to, if you have any feedback on the plugins, since things are still very much subject to change.
