### ISSUE TITLE
Extend CI workflow to push docker image to github container registry as well

### ISSUE THREAD

**Issue by simskij** [loadimpact/k6#1622]
Given that DockerHub has made some changes in its pricing and added some limits to free users, we should consider pushing our docker images to GitHub Packages as well. If nothing else than for having a mirror available if someone hits the limit with DockerHub.

**Comment by salem84** [comment]
Hi, I would like to change circleci pipeline in order to use Github Container Registry instead Github Packages, because as described [here](https://docs.github.com/en/free-pro-team@latest/packages/getting-started-with-github-container-registry/migrating-to-github-container-registry-for-docker-images) GitHub Container Registry supersedes the existing Packages Docker registry and is optimized to support some of the unique needs of containers.
What do you think about it?

**Comment by na--** [comment]
@salem84, please wait a few days - we plant to merge https://github.com/loadimpact/k6/pull/1640 today, and use only GitHub actions for CI. Then pushing the docker images to both the docker hub and the github container registry will be easier. And, as things stand, we'll probably accept such a PR.

**Comment by salem84** [comment]
Sure @na-- 
Yesterday, after I wrote this comment, I have seen other `ci` issues and I have found also #1640 
We will keep in touch and decide after merge!

**Comment by imiric** [comment]
#1689 closes this. Thanks @salem84!
