### ISSUE TITLE
K6 script giving timeout in Azure devops

### ISSUE THREAD

**Issue by chandanp041** [loadimpact/k6#1728]
**Setup**

We are using [K6][1] tool for Load testing our API. 
Locally scripts work perfectly fine with virtual users up to 50

**problem statement**

While running the same script in Azure devops using [K6][2] task  and virtual user 15 for duration 60s most of the request (almost 90%) is failing because of timeout and following is the error :

**level=warning msg="Request Failed" error="Get \"https://xxxxx\": dial tcp xxxx: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."**

Not sure

**a) What is causing the timeout?**

**b) What are the other options?**

PS: Api is behind Api Management Service in Azure and load test works locally fine even on 10 times higher load

  [1]: https://k6.io/
  [2]: https://marketplace.visualstudio.com/items?itemName=k6.k6-load-test

**Comment by imiric** [comment]
This is more suitable as a support question on the [community forum](https://community.k6.io/), and we also saw your [Stack Overflow question](https://stackoverflow.com/questions/64893067/k6-script-failing-in-azure-devops), so there's no need to ask this in several places.

Are you sure this is specific to k6? The error indicates k6 is not able to connect, so have you tried `curl`, `netcat`, or any other way to confirm you can connect to the service in Azure?

**Comment by na--** [comment]
I see that there's some discussion occurring in the linked StackOverflow question and it's looking likely that it's a networking issue. The only thing on the k6 side that might have affected this is https://github.com/loadimpact/k6/issues/548#issuecomment-731245076, though that seems very unlikely to me. Since we merged https://github.com/loadimpact/k6/pull/1734, that can also be ruled out by running the `master` k6 Docker image, and has another open issue tracking the underlying cause. 

So, I'm closing this issue, but we can always reopen it or open a new one if it turns out that this was indeed an unresolved k6 bug.
