### ISSUE TITLE
Http response.request.headers are missing "host" value 

### ISSUE THREAD

**Issue by kenewbie** [loadimpact/k6#1740]
If you set a value for "host" in the header of a http.post request, that value gets stripped from the response-objects .request.header property. Minor issue but I was asked to report it.

## Environment
k6 v0.28.0 ((devel), go1.14.9, windows/amd64)

## Steps to Reproduce the Problem
```
import http from "k6/http";

export default function main() {
    let r = http.post("https://localhost", "body", { headers: { "foo": "bar", "host": "https://some.domain.com" } });
    console.log(JSON.stringify(r.request.headers));
}

```

**Comment by na--** [comment]
Thanks for reporting this! I suspect this issue is caused by this `switch`: https://github.com/loadimpact/k6/blob/62665cfa87899ae210578276d7e16b4f4dd8fd7c/js/modules/k6/http/request.go#L287-L295

And maybe a simple `fallthrough` would be enough to fix it, but whoever ends up doing that should read up on the Go `net/http` docs and maybe the RFC, as well as test things thoroughly, so we don't mess up something else.
