### ISSUE TITLE
Windows MSI is blocked by Microsoft Defender because it is not signed

### ISSUE THREAD

**Issue by BenjaminAbt** [loadimpact/k6#1786]
Downloading the latest msi with Microsoft Edge will be blocked by Microsoft Defender, because "it could harm your device"

![image](https://user-images.githubusercontent.com/6189336/104125144-35827600-5355-11eb-9f5b-7c5d278aba72.png)

Looks like the issue is just because the MSI is not signed
![image](https://user-images.githubusercontent.com/6189336/104125270-eee14b80-5355-11eb-8279-c0fd8bbfb038.png)
This is fundamentally not a big deal; however, there are now customers who cannot bypass the corresponding error due to company settings.

## Environment

- k6 version: 0.29.0 amd64
- OS and version:  Microsoft Windows Version 10.0.19042.685
- Microsoft Edge Version 89.0.752.1 (Official build) dev (64-bit)

## Expected Behavior
Download should be trusted; even for developers who cannot use a Docker container in their environment.

## Actual Behavior
Download is blocked by Edge aka [Microsoft Defender Smartscreen](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview?WT.mc_id=AZ-MVP-5001507)

**Comment by imiric** [comment]
Thanks for reporting this @BenjaminAbt, but I'll close it as it's a known issue, see #1034.

This was recently fixed in #1746 and will be part of the upcoming v0.30.0 release, due later this month. That said, even with a signed binary the SmartScreen warning will continue to appear until Microsoft has determined that the k6 certificate and application can be trusted, which might take a few weeks/months.
