### ISSUE TITLE
Using InfluxDB output affects the test

### ISSUE THREAD

**Issue by geekdave** [loadimpact/k6#182]
Maybe this is just [the observer effect](https://en.wikipedia.org/wiki/Observer_effect_(physics)) in action, but I thought I'd run it by the experts 😉 

# Summary

Turning on InfluxDB output seems to:

1. reduce the total iterations in a given run
2. increase latency (`http_req_duration`)

# With InfluxDB output turned on

```
d@k2med:~/k6-v0.11.0-linux64$ ./k6 run --vus 50 --duration 10s --out influxdb=http://influxdb.xxxxxxx.com:8086/k6  http://punchingbag.xxxxxxx.com:8080

          /\      |‾‾|  /‾‾/  /‾/
     /\  /  \     |  |_/  /  / /
    /  \/    \    |   _  |  /  ‾‾\
   /          \   |  | \  \ | (_) |
  / __________ \  |__|  \__\ \___/  Welcome to k6 v0.11.0!

  execution: local
     output: influxdb (influxdb.xxxxxxx.com:8086)
     script: [cmdline] (url)

   duration: 10s, iterations: 0
        vus: 50, max: 50

    web ui: http://127.0.0.1:6565/

      done [==========================================================]        10s / 10s

    http_req_blocked......: avg=28.12µs, max=29.02ms, med=1.2µs, min=755ns, p90=2.13µs, p95=2.47µs
    http_req_connecting...: avg=1.32µs, max=8.76ms, med=0s, min=0s, p90=0s, p95=0s
    http_req_duration.....: avg=5.77ms, max=219.84ms, med=3.35ms, min=450.81µs, p90=14.2ms, p95=19.74ms
    http_req_looking_up...: avg=24.64µs, max=22.57ms, med=0s, min=241.86µs, p90=0s, p95=0s
    http_req_receiving....: avg=172.49µs, max=53.8ms, med=44.54µs, min=27.08µs, p90=141.06µs, p95=246.64µs
    http_req_sending......: avg=32.72µs, max=29ms, med=9.5µs, min=5.67µs, p90=20.67µs, p95=26.85µs
    http_req_waiting......: avg=5.54ms, max=219.57ms, med=3.22ms, min=376.48µs, p90=13.59ms, p95=18.96ms
    http_reqs.............: 86361
    iterations............: 86361
    vus...................: 50
    vus_max...............: 50
```

# With InfluxDB output turned off

```
d@k2med:~/k6-v0.11.0-linux64$ ./k6 run --vus 50 --duration 10s http://punchingbag.xxxxxxx.com:8080

          /\      |‾‾|  /‾‾/  /‾/
     /\  /  \     |  |_/  /  / /
    /  \/    \    |   _  |  /  ‾‾\
   /          \   |  | \  \ | (_) |
  / __________ \  |__|  \__\ \___/  Welcome to k6 v0.11.0!

  execution: local
     output: -
     script: [cmdline] (url)

   duration: 10s, iterations: 0
        vus: 50, max: 50

    web ui: http://127.0.0.1:6565/

      done [==========================================================]        10s / 10s

    http_req_blocked......: avg=17.31µs, max=23.35ms, med=1.17µs, min=734ns, p90=2µs, p95=2.39µs
    http_req_connecting...: avg=728ns, max=3.12ms, med=0s, min=0s, p90=0s, p95=0s
    http_req_duration.....: avg=3.96ms, max=48.55ms, med=2.49ms, min=430.59µs, p90=8.73ms, p95=14.25ms
    http_req_looking_up...: avg=18.78µs, max=24.53ms, med=0s, min=0s, p90=0s, p95=0s
    http_req_receiving....: avg=165.59µs, max=25.16ms, med=41.03µs, min=27µs, p90=177.64µs, p95=316.99µs
    http_req_sending......: avg=24.2µs, max=24.45ms, med=9.16µs, min=5.34µs, p90=20.07µs, p95=36.15µs
    http_req_waiting......: avg=3.75ms, max=48.5ms, med=2.4ms, min=386.03µs, p90=7.98ms, p95=13.31ms
    http_reqs.............: 125726
    iterations............: 125726
    vus...................: 50
    vus_max...............: 50
```

# Possible solutions

1. Use a UDP protocol like [statsd](https://github.com/etsy/statsd) to reduce the overhead on the load generator
2. Batch up the metrics into 1 sec buckets and only emit the aggregates for those buckets

Either of these would also significantly reduce the load on the influxDB server itself (mine is running on a micro instance and crashes under the load of 50 VUs)

I'm happy to dive in and work on a solution, if it would be helpful.   Thanks!

**Comment by liclac** [comment]
Hm, interesting - InfluxDB collection *does* introduce a bit of load on the emitting system because every k6 sample has to be turned into an InfluxDB sample, but it shouldn't be nearly this noticeable - it spawns a separate goroutine that's shipped samples every ~10ms, completely out of band from any VU goroutines… but you may be onto something here.

The collector does batch samples up in 1s buckets, but that's a rather arbitrary number - perhaps [tweaking it](https://github.com/loadimpact/k6/blob/master/stats/influxdb/collector.go#L35) could yield better performance? UDP is an option as well, but as I recall, when we tried feeding InfluxDB samples that way it actually resulted in a significant number of them straight-up vanishing into the ether.

This is something I'm really interested in optimizing as much as possible, because it will be integral to clustered setups, but there are some other deadlines coming up before I can get on it - the InfluxDB code isn't *nearly* as optimized as it deserves to be… but I can certainly help in any way I can.

Just to be absolutely sure, check that the usual suspects aren't skewing the results here unnecessarily:

* There are no lingering `TIME_WAIT` sockets (check `ss -s` on Linux)
* The first test didn't populate caches that are now serving things faster to the second one
* There are no cron jobs or similar messing things up

**Comment by geekdave** [comment]
@liclac Just revisiting this.  It's worth noting that my InfluxDB server is currently residing on a very underpowered t2.micro instance.  If Influx is slow-to-respond to each 1s bucket that's posted to it from the k6 client, would that explain the slowdown?  i.e. is k6 blocking on responses from Influx in some way?

**Comment by carlwright4** [comment]
(#182)

On May 8, 2017 6:27 PM, "Dave Cadwallader" <notifications@github.com> wrote:

@liclac <https://github.com/liclac> Just revisiting this. It's worth noting
that my InfluxDB server is currently residing on a very underpowered
t2.micro instance. If Influx is slow-to-respond to each 1s bucket that's
posted to it from the k6 client, would that explain the slowdown? i.e. is
k6 blocking on responses from Influx in some way?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/loadimpact/k6/issues/182#issuecomment-300008719>, or mute
the thread

**Comment by mikkiweesenaar** [comment]
Currently I am trying to get an environment up on my Macbook Pro Retina 2015 (2.5ghz I7, 16GB RAM). I will try to execute a similar scenario and post my results here.

**Comment by jordandlaman** [comment]
I _think_ I am encountering a similar issue.  When running my volume tests with influx  + grafana/chronograf visualizing the data the test will have serious gaps in the requests per second.  At first I believed I was being rate limited by cognito but we replaced cognito with our own jwt authorizer lambda and it is extremely performant.  The other thing that happens is the response time for all the endpoints starts sky rocketing up.  They usually sit in the 90 -150 ms range but will balloon up to 20s across the board.  I did not encounter this problem a few months ago while running tests and have had to disable outputting results to influxdb for the tests to return metrics worth anything.  Luckily we have cloudwatch but it isn't ideal as cloudwatch doesn't have insight into the response times of all the endpoints outside of AWS.
