### ISSUE TITLE
Ship metrics to Influxdb

### ISSUE THREAD

**Issue by fnzv** [loadimpact/k6#1830]
## Feature Description
It would be very cool to have the possibility to ship metrics directly into a Influxdb timeseries db, such features are available also in Jmeter via plugins in order to create dashboards and visualize tests over time.

## Suggested Solution (optional)
I did not go deep into your code but if you can ship the metrics via Go could be easy. (i already tested the influxdb libraries and they are pretty straight forward)

The very simple client lib is this one: go get "github.com/influxdata/influxdb1-client/v2" 

I tested it on some projects and they work flawlessly, dunno if you have some other costraint because as i said i didn't have a look at the codebase of k6

Looks a solid project glad to have found it now

Edit 1:
I read quickly your doc and i saw only this link https://k6.io/docs/results-visualization/influxdb-+-grafana
So i suppose some of you may already tought of it or just done it inside JS

**Comment by na--** [comment]
As you seem to have discovered, k6 already supports sending metrics to InfluxDB. You've found the docs, and the actual code is located here: https://github.com/loadimpact/k6/tree/master/stats/influxdb

It's indeed using the library you suggested: https://github.com/loadimpact/k6/blob/46d53d99deba98add23079df93579408fa7ea094/stats/influxdb/collector.go#L30

Though we'll probably update to the one for InfluxDB 2 soon: https://github.com/loadimpact/k6/issues/1730

I'll close this, since there doesn't seem to be any new requirements here.
