### ISSUE TITLE
Kafka / Influxdb format: influxdb's ConcurrentWrites must be a positive number

### ISSUE THREAD

**Issue by ivanape** [loadimpact/k6#1913]
Running a K6 load tests with following configuration:

```
#!/bin/bash
export K6_INFLUXDB_TAGS_AS_FIELDS=tag1,tag2
export K6_INFLUXDB_CONCURRENT_WRITES=5
export K6_KAFKA_BROKERS=localhost:29092,localhost:29093,localhost:29094
export K6_KAFKA_TOPIC=metrics
export K6_KAFKA_FORMAT=influxdb
export K6_KAFKA_PUSH_INTERVAL=1s
export K6_OUT=kafka

k6 run demo.js --verbose
```

Shows following error:

```
DEBU[0000] Starting executor run...                      duration=1m0s executor=constant-vus scenario=default type=constant-vus vus=100
ERRO[0001] Kafka: Couldn't format the samples            error="influxdb's ConcurrentWrites must be a positive number"
ERRO[0002] Kafka: Couldn't format the samples            error="influxdb's ConcurrentWrites must be a positive number"**
```

## Environment

- k6 version: v0.31.0 ((devel), go1.16, darwin/amd64)
- OS and version: macOS 11.2.1

## Expected Behavior

Send k6 metrics in InfluxDB format.

## Actual Behavior

Raise an error.

**Comment by na--** [comment]
@ivanape, thanks for reporting this! I'm sorry to say that this is a regression I introduced in k6 v0.31.0 with https://github.com/loadimpact/k6/pull/1869... :disappointed: The problem occurs because of the `K6_KAFKA_FORMAT=influxdb` option, there was a bug in the InfluxDB configuration merging for the Kafka output...

@mstoykov fixed the issue with https://github.com/loadimpact/k6/pull/1914, and we'll likely merge it in `master` later today. So, until we release k6 v0.32.0 on May 3rd, you can work around this bug in any of these ways:
- roll back to k6 v0.30.0
- after https://github.com/loadimpact/k6/pull/1869 is merged, use the `loadimpact/k6:master` Docker image, which is built on every k6 `master` commit and is reasonably stable
- do not use `K6_KAFKA_FORMAT=influxdb` and use the default `json` format instead
- use the `influxdb` output directly, not through Kafka

**Comment by ivanape** [comment]
Thank you @na-- and @MStoykov  for your detailed feedback and for the quick resolution of the incident.
