### ISSUE TITLE
Mechanism for extending options from modules

### ISSUE THREAD

**Issue by robingustafsson** [loadimpact/k6#240]
One thing I've noticed when creating tests is that it would be nice to extend the options from modules in an easy way, especially thresholds in my case.

To show an example of what I mean, let's say we have a main.js like so:
```js
import { group } from "k6";
import http from "k6/http";

// Units/Pages
import { testIndexPage } from "./units/index.js";

// Options
export let options = {
    stages: [
        { duration: "30s", target: 10 },
        { duration: "30s" },
        { duration: "30s", target: 0 }
    ]
};

// Scenario
export default function() {
    group("Front page", function() {
        testIndexPage();
    });
}
```
and a index.js file in a units/ sub directory:
```js
import { check, group, options  } from "k6";
import http from "k6/http";

// Constants
const baseURL = __ENV.BASE_URL || "http://test.loadimpact.com";
const mainURL = `${baseURL}/`;
const thresholdP95 = 100;

// Options
let pageThresholds = {};
pageThresholds[`http_req_duration{url:${mainURL}}`] = [`p(95)<${thresholdP95}`];

options.extend("thresholds", pageThresholds);

// Tests
export function testIndexPage() {
    ...
}

export default function() {
    testIndexPage();
}
```
I'd like to be able to do something along the lines of what is done on line 13 in index.js above (`options.extend("thresholds", pageThresholds)`, with `options` imported from `"k6"`).

Specifying options using `options.extend(...)` should be possible to use as an alternative to the top-module `export let options = {...};`, meaning index.js should work both as a module/unit used in a larger test and as a standalone test case.

The solution I've used thus far is to export the `pageThresholds` and then merge thresholds from several modules into one JS object that gets set as the `thresholds` option.

**Comment by liclac** [comment]
This is a very interesting idea, but I'd like to propose an alternate implementation.

With this approach, imagine this:


```js
// mod1.js
options.extend({ vus: 10 });

export default function() {}


// mod2.js
options.extend({ vus: 20 });

export default function() {}


// main.js
import mod1 from "./mod1.js";
import mod2 from "./mod2.js";

export default function() {
  group("mod1", mod1);
  group("mod2", mod2);
}
```

The use of `vus` is for illustration, but the value of it now depends on the order `mod1.js` and `mod2.js` are imported in, and if the change you're looking for is in a file that's imported from a file that's imported from a file that's imported from main.js, it may become hard to actually identify what's going on with your options.

I'm thinking of opening up to something like this:

```js
// mod1.js
export let options = {
  thresholds: { "http_req_duration{tag:mod1}": ["avg<500"] },
};

export default function() { }


// mod2.js
export let options = {
  thresholds: { "http_req_duration{tag:mod2}": ["avg<250"] },
};

export default function() { }


// main.js
import mod1, { mod1opts } from "./mod1.js"
import mod2, { mod2opts } from "./mod2.js"

export let options = [{
  vus: 10,
  thresholds: {
    "http_req_duration": ["avg<100"],
  },
}, mod1opts, mod2opts];

export default function() {
  group("mod 1", mod1);
  group("mod 2", mod2);
}
```

This makes the ordering and origin explicit. We already have the means to intelligently merge options (...aside from a few cut corners, like how `thresholds` isn't actually merged but replaced right now...), we can take that and expose it like this. Of course, it'd work recursively as well:

```js
// condensed, subsequent values would most likely be imported
export let options = [
  { vus: 10 },
  { thresholds: { "my_metric": "avg<100" } },
  [
    { thresholds: { "my_metric": "p(95) < 50" } },
    { thresholds: { "my_metric": "p(90) < 70" } },
  ],
};

**Comment by robingustafsson** [comment]
@liclac Yeah, I solved it by importing the options from the modules and then `Object.assign(...)` them together in the main file. More explicit yes, but also a more verbose way of doing it IMO.  A thought, perhaps an `options.extend(...)` API could be limited to those options that are naturally extendable?

**Comment by liclac** [comment]
I'm honestly not a fan of that...

We *could* add a function to add a threshold, specifically (we just need a good syntax for it), but I don't like the idea of having nonobvious rules for option merging that will sooner or later shoot someone in the foot.

**Comment by cstyan** [comment]
@robingustafsson @liclac 
I'm a bit lost on this one. 

Is importing exported options from modules via multiple files supported already? `NewBundle` only takes in one src file. `We already have the means to intelligently merge options` where is this happening?

**Comment by robingustafsson** [comment]
@cstyan No, it's not supported yet to import options from modules (besides the main one). The stuff we have around merging of options is here:
- `Apply()`: https://github.com/loadimpact/k6/blob/master/lib/options.go#L205
- And how we cascade config file, CLI and script options: https://github.com/loadimpact/k6/blob/master/cmd/archive.go#L76

So right now the cascading code just replaces options when merging, so I'd say "intelligently" is overstating it slightly :)

Feel like we maybe need to create a `type` for the Thresholds option and handle `UnmarshalJSON` for it to support the expanded definition of allowed values for the `thresholds` script option.

**Comment by cstyan** [comment]
@robingustafsson 

Sorry, I still have't been able to get this working. I've tried messing with the code in both `Options` and `Bundle`, including the tests for those.

What I was trying is to get `Options.Apply` to append thresholds to `stats.Thresholds.Thresholds` since that's an array, rather than simply overwriting what is already in there for each call to `Apply`. I think I'm still missing something in the options parsing/json unmarshaling. I still don't understand how exports are passed to options parsing and then into bundle.

**Comment by robingustafsson** [comment]
@cstyan Ah sorry, I see I got things mixed up in my last comment with the JSON unmarshaling. I was for some reason thinking of the `thresholds` property only and not that the whole `export let options` could be either an `[{...}, {...}, ...]` or an `{...}`. Probably not the most elegant, but what I think we can do is to add custom unmarshaling of the `Options` struct and then handling the merging of thresholds in `Options.Apply()` as you said, so something like this for the unmarshaling:

1. The `options` are extracted from JS after a first run of the JS code (global scope/"init code"): https://github.com/loadimpact/k6/blob/master/js/bundle.go#L123

2. We do custom unmarshaling to handle both the `[{...}, {...}, ...]` and `{...}` case:
```go
func (o *Options) UnmarshalJSON(data []byte) error {
	var f interface{}
	if err := json.Unmarshal(data, &f); err != nil {
		return err
	}
	switch f.(type) {
	case []interface{}:
		// handle multiple options objects in array, chain of Apply()s
	case map[string]interface{}:
		// handle single options object
	}
	return nil
}
```
The above is likely too naive and maybe creating a new type for `Options` in the `Bundle` is needed so we can still use the transparent JSON unmarshaling of the `Options` struct but just wrap the decomposition of the potential `[{...}, {...}, ...]` case into multiple unmarshalings of the `{...}` case or something like that.

**Comment by cstyan** [comment]
@robingustafsson okay, making some progress. The question I still have is how do we want to handle merging of multiple `Options` struct into a single struct? Do we want to change fields on the `Options` struct? Are we merging all fields, or just thresholds?

**Comment by robingustafsson** [comment]
@cstyan Good question, I think the most obvious from a user perspective is if we replace those options that we don't merge.

I think @ppcano has some opinions on this as well.

**Comment by na--** [comment]
Since the exported `options` are a purely JS object, and it can be a pretty complicated one (see `stages`, `thresholds`, `ext` and some planned future extensions like multiple outputs and the arrival-rate based executor), I think any solution here would be much better as a JavaScript helper function, not as something in the k6 Go code. And even then, I'm not sure we should actually do anything "official" as part of k6, since users' configuration needs here could be quite diverse - it would be very difficult to handle most possibilities with a fixed API. 

I feel it should be enough to improve the `import` support (i.e. the relevant parts of  https://nodejs.org/api/modules.html#modules_all_together, as mentioned in [multiple issues](https://github.com/loadimpact/k6/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Ajs-compat+modules)) and JS compatibility in general, so users can do something like:

```js
export let options = {
    stages: import `./config/${__ENV.somevar}.conf.json`
};
```
  
...or pretty much any configuration merging and extension that they want. That way they can add their own flexibility with just a short wrapper function or two, if they even need any extra functions at all - [`Object.assign()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) and [`Array.concat()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat) would probably be enough for most of the cases.

Closing this and the [connected PR](https://github.com/loadimpact/k6/pull/490/files) for now, though I wouldn't mind reopening them if there's a good reason to handle these things in the Go codebase that I've missed.
