### ISSUE TITLE
Set No of TCP Conns

### ISSUE THREAD

**Issue by aidylewis** [loadimpact/k6#245]
Any way of setting the number of TCP connections without interfering with the ulimit?

**Comment by liclac** [comment]
Could you elaborate?

By default, connections are reused between VU iterations because otherwise we chew through most OSes' default ulimit far too quickly to be of any use; pass `--no-connection-reuse` to disable this behaviour. Are you asking for a way to limit the number of TCP connections used when they're not reused?

**Comment by robingustafsson** [comment]
Duplicate of https://github.com/loadimpact/k6/issues/215?

**Comment by liclac** [comment]
Poke.

**Comment by aidylewis** [comment]
Can be done through iptables.

**Comment by liclac** [comment]
Alright, closing this then.

**Comment by aidylewis** [comment]
Can be done with the **noConnectionReuse** flag. I tested with one request == one TCP connection and socket statistics.
