### ISSUE TITLE
pdf exporter

### ISSUE THREAD

**Issue by aidylewis** [loadimpact/k6#266]
I'd like a basic pdf which would give me response times in percentiles, virtual users, requests per second etc. Graphs would be nice but that might be the cut-off point between LGPL and money making.  The Gatling graphs look great but irritate clients because of their size. Clients just used to look at the mean (misleading), I'd advise them to look at p95, p99

**Comment by na--** [comment]
I'll close this because it's out of scope for k6, at least for the foreseeable future. I think this functionality would be better as part of an external tool that takes the k6 metrics (either raw data from an output like a JSON file, InfluxDB, or Load Impact Insights, or the summary stats when [this](https://github.com/loadimpact/k6/issues/351) or [this](https://github.com/loadimpact/k6/issues/355) feature is implemented) and visualizes them.
