### ISSUE TITLE
Add Elm transpilation support to the JS runner

### ISSUE THREAD

**Issue by ghost** [loadimpact/k6#292]
1. Functional and thus immutable
2. Errors at compile time instead of runtime
3. High quality error messages
4. Minimal, yet expressive (less clutter for even simple tests)

**Comment by aidylewis** [comment]
1. Functional and thus immutable
2. Errors at compile time instead of runtime
3. High quality error messages
4. Minimal, yet expressive (less clutter for even simple tests)

**Comment by neilstuartcraig** [comment]
@aidylewis - Just a quick note/idea, not to distract or detract from the Elm idea but something you might (or might not) want to check out as these should work straightaway:

if you want a fast way to get proper immutability, you could try https://facebook.github.io/immutable-js/ in your K6 scripts. It doesn't have quite the same featureset or guarantees as Elm but should work right now. There are also more complete/extreme FP libs for JS such as http://ramdajs.com/ which might be what you're looking for.

You could also potentially use eslint in a build step to fail if vars are mutated and/or if any other rules fail. There are tons of rules you can configure: https://eslint.org/docs/rules/.
I use eslint with flow types so i can have provable data type consistency. You can configure things to warn or to fail on build if there is type coercion and/or to throw runtime errors. 

One of the best guarantees Elm provides is no runtime errors due to the compiler - i like this principle a lot. You could probably approximate but not exactly do this in JS.

Hope that's helpful, apols if not :-)

**Comment by liclac** [comment]
If anyone wants to take a dig at this, you could just add Elm transpilation support to the JS runner.

**Comment by simskij** [comment]
Being able to transpile elm to javascript using webpack and an elm loader will likely be more than enough for most users.
https://github.com/elm-community/elm-webpack-loader
