### ISSUE TITLE
Failed to send metrics to cloud

### ISSUE THREAD

**Issue by dream83619** [loadimpact/k6#316]
I got a 'WARN[0048] Failed to send metrics to cloud               error="An error occurred talking to Load Impact cloud"' when I output the result to the cloud, I already set the K6CLOUD_TOKEN properly, and my test was also shown in the insight but has no data.

**Comment by artych** [comment]
Hello @dream83619, 
could you share your script (or simplified version), so I'll try to replicate the issue?

**Comment by dream83619** [comment]
this is my code, thank you

import http from "k6/http";
import { check, sleep } from "k6";

export let options = {
    vus: 10,
    duration: "30s"
};

const BASE_URL = 'http://www.xiaoshuaizhi.com/xiaoshuaizhi-mobile/';
const TOKEN = "bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjI1MDU2MjQ3MDUsInVzZXJfbmFtZSI6IjI1MDMzNTI5LTlhMzctNDA0ZC04MDZlLWU3YmViMzg3MGVlNSIsImp0aSI6IjUzZjk4MTU3LTAxNzEtNGFmZS1hMDgzLTYxZmEzMTVkMWEyOCIsImNsaWVudF9pZCI6Im1vYmlsZSIsInNjb3BlIjpbIm1vYmlsZSJdfQ.XYKfhv-OuprdL_0mCZAnCbb59-Sey45nBlb_nMQ9ZIg";

export default function() {

    let res = http.get(`${BASE_URL}users/me`, { headers: { "Authorization": TOKEN } });
    check(res, {
        "status was 200": (r) => r.status == 200,
    });
};

**Comment by artych** [comment]
I've run your script several times and once I've detected the issue above. To avoid it I'd recommend you always to add some `sleep` time between iterations, like in the example above. 
Without some delay fast responses from system under test causes k6 performs huge amount of reqs and finally overflows LoadImpact Insights by the requests raw data.
Try to add 
```
sleep(1);
```
after `check(...);` and run it, hope it helps. 
If you have concerns about connectivity (as you mentioned government firewall) I'd say you can reach Load Impact cloud, otherwise you'll see another error message. So you just have to check your target system by running `curl` request manually or by using `postman`.

**Comment by dream83619** [comment]
I add the `sleep(1) `code, and the error is gone. thank you for your quick response.
k6 is really an excellent work, and i wish you can continue to make it more and more excellent, and I will recommend our team to use it in the future, thank you.
