### ISSUE TITLE
Simplified one-check syntax

### ISSUE THREAD

**Issue by ragnarlonn** [loadimpact/k6#33]
```
check("name", () => /* ... */);
```
*Imported from https://trello.com/c/jW4KQLOw/109-simplified-one-check-syntax*

**Comment by liclac** [comment]
The semantics of this are getting complicated…

Any kind of expression is valid in a check, callables expanded to one… which means we can't turn `check("name", expr)` into `check(null, {"name": expr})`, because `check("name", {})` would be ambiguous - is this a check called "name" with the (falsy) value `{}`, or an (empty) list of checks to be done on the string "name"?

We *could* turn `check({"name": expr})` into `check(null, {"name": expr})`, but then you get an ambiguity when you add tags - there would be no way to tell if `check({name: expr}, {tag: value})` should run the check "tag" on the object `{name:expr}`, or run the check "name" on null and tag the result with tag=value.
