### ISSUE TITLE
SSL support and auth for the API

### ISSUE THREAD

**Issue by ragnarlonn** [loadimpact/k6#34]
Checklist
- [ ] Serve API over SSL
- [ ] Token authentication
- [ ] Client cert authentication

*Imported from https://trello.com/c/cNVU86AL/110-ssl-support-and-auth-for-the-api*

**Comment by aidylewis** [comment]
SSL client cert support is really important for us as we now need to do some HTTP2 testing.

**Comment by bagder** [comment]
@aidylewis I think you might be confusing matters here. client cert is not used with HTTP/2. They're almost mutually exclusive since **client** certs authenticate a connection to a server while HTTP/2 is made for doing many "independent" stream over that connection. Browsers that do client cert auth today do that over HTTP/1.1.

**Comment by aidylewis** [comment]
@bagder You're correct. Thanks for the heads-up.

**Comment by liclac** [comment]
@robingustafsson Can we have a milestone for this?

**Comment by robingustafsson** [comment]
@liclac Is this not two different issues, one regarding SSL and auth for the internal k6 API and one for supporting SSL client certs in the JS API?

**Comment by liclac** [comment]
Yeah, two issues. Let's use #206 for client auth, can someone open another issue for HTTPS support in the API? The comments on this one are currently a little confusing.
