### ISSUE TITLE
Add support for streaming stats

### ISSUE THREAD

**Issue by StephenRadachy** [loadimpact/k6#344]
Lots of people front their metrics services with message queues like Apache Kafka, ZeroMQ, ActiveMQ, RabbitMQ, or NATS. It would be awesome and more performant to have this built-in to k6 itself instead of having to build out a separate message producer.

**Comment by aidylewis** [comment]
Isn't this out of the realm of a load-test tool, which runs a lot of threads/processes and reports mainly on response times.

**Comment by liclac** [comment]
I like this idea, samples are already streamed internally, so it'd be easy to make this work from a collector.

**Comment by jmccann** [comment]
Should this issue remain open or be closed now that #617 is finished and provides an initial implementation of this with kafka?  If others want other messaging services supported they at least now have an example they can use to PR their own.  😉

**Comment by na--** [comment]
Yeah, @jmccann I agree, I'm closing this issue since the kafka output collector was merged. 

I'd also like to invite people who want support for some other message queue, even if they can't contribute the code themselves, to open a new issue with a request for the specific message queue they'd like to have support for. And if someone has already created an issue requesting something, let's say RabbitMQ for example, leave a :+1: in that issue so we know how many users would like support for it.
