### ISSUE TITLE
Expose Request information on Response

### ISSUE THREAD

**Issue by marklagendijk** [loadimpact/k6#440]
In most HTTP request libraries a `response` has a `request` property. This is useful for debugging, logging, generating reports etc.
In k6 this would be very useful for usage with `check`. 

I would propose the following approach:

1. Create an `HTTPRequest` struct.
2. Instantiate this struct in `HTTP.Request` based on all args.
3. Add a `Request` property on the `HTTPResponse` struct.

**Comment by robingustafsson** [comment]
Good idea. What fields should the `request` property have?

I can think of the following as being useful from the top of my head:
- `method`
- `url`
- `headers`
- `cookies`
- ?

Not sure if `body` is needed?

**Comment by marklagendijk** [comment]
@robingustafsson I agree. I would also include `body` as long as it does not affect performance.

**Comment by robingustafsson** [comment]
Yeah, I guess including `body` shouldn't be a problem as it should just point to the same memory already used for making the request, so no copying or extra memory should be necessary.

**Comment by cstyan** [comment]
Adding the `request` to `response` is simple enough: https://github.com/cstyan/k6/commit/c49a5faff26e71eb2926db453f5a3c5f1b0d2705

However I'm having trouble understanding the existing tests/where anything from `HTTPResponse` is exposed to the user via JavaScript. If there's something I'm missing let me know, otherwise I'm thinking the proper way to test this is outside the existing tests in `response_test.go` by just calling `request`?

**Comment by marklagendijk** [comment]
@cstyan in `http_request_test.go` there are tests that do a request and check the response. You could just add extra checks to the existing tests, or add some separate tests.
Currently the separation of the tests is:
- _Methods_ from `http_request.go` =>  `http_request_test.go`
- _Methods_ from `response.go` => `response_test.go`

So the appropriate place for these tests would be `http_request_test.go`

**Comment by robingustafsson** [comment]
Reopening for a bounty payout to @cstyan
