### ISSUE TITLE
Issue running example code in docker

### ISSUE THREAD

**Issue by Miladinho** [loadimpact/k6#444]
Running example test script from docs via docker returns error:

` level=error msg="script must export a default function"`

Using latest loadimpact/k6 image

**Comment by robingustafsson** [comment]
@Miladinho What is the full command you're using to run k6? Make sure you include the `-i` when running Docker if reading the script from stdin, something like: `docker run -i loadimpact/k6 run -< script.js`

**Comment by Miladinho** [comment]
`docker run loadimpact/k6 run - < script.js`

**Comment by robingustafsson** [comment]
Thanks, then you need to add the `-i` in there otherwise the container won't have access to read the script from stdin (the `-` tells k6 to read the script from stdin, and the `<` pipes the script into the container).

So try:
`docker run -i loadimpact/k6 run -< script.js`

Did you get the command from the docs?

**Comment by Miladinho** [comment]
@robingustafsson 

I'm relatively new to docker but that makes perfect sense, i've been using the -i and -t flags for input. Thank you!

**Comment by robingustafsson** [comment]
@Miladinho Easily missed, I've been bitten by it myself.

I'm actually gonna add a note to the docs about this, as we're at least two who've run into it now :)
