### ISSUE TITLE
Test wide tags

### ISSUE THREAD

**Issue by ChristofferNicklassonLenswayGroup** [loadimpact/k6#461]
Hi.

So our setup we aim to run k6 agains all our microservices and have them store its output in influx.
we dont want to have a DB per test so we are using the tags to define what microservice and have added selectors to grafana to show for only the selected test.
vus are one table where the tags are not set and there by the grafanaboard will show all  values not only the ones from selected service.

So we would like to see that all data thats it store with --out  would have the tags added.

![skarmbild fran 2018-01-15 12-37-09](https://user-images.githubusercontent.com/33247910/34940696-d7f2b0ec-f9f0-11e7-9b53-cac6fe4fbc2e.png)

**Comment by robingustafsson** [comment]
I suggest we add a CLI option `--tag myTag=hello` or similar (that can be specified multiple times) as well as a new option `tags` (`export let options = { tags: { "myTag": "hello", "myTag2": "world" } };`) so that one can specify tags that should be set on at least the engine and runner emitted metrics like `vus`, `iterations`, `checks` etc. (see https://github.com/loadimpact/k6/blob/master/lib/metrics/metrics.go), but maybe on all metrics to be consistent and for allowing to filter on such tags when using Grafana, Load Impact Insights etc.
