### ISSUE TITLE
Make use of a local http server for tests

### ISSUE THREAD

**Issue by cstyan** [loadimpact/k6#464]
current http tests rely on `httpbin.org`, we should make use of a local http server (perhaps written in go) so that we're not relying on an external resource, and to possibly support testing `CONNECT` and `TRACE` methods

https://github.com/loadimpact/k6/pull/451#issuecomment-357296743

**Comment by na--** [comment]
I'll start to work on this today. I could find two go libraries ([1](https://github.com/ahmetb/go-httpbin), [2](https://github.com/mccutchen/go-httpbin)) that implement httpbin-like functionality. I chose the second one for now because of [this](https://github.com/mccutchen/go-httpbin#motivation--prior-art) and I've already used it in a test [here](https://github.com/loadimpact/k6/pull/523), it seems to be [very easy to integrate](https://github.com/loadimpact/k6/blob/a0246467ad76e312beb9e67a70f0f52b0f6ca5ef/core/engine_test.go#L495-L496). Since the [migration](https://github.com/loadimpact/k6/pull/526) to [`dep`](https://github.com/golang/dep) it's already vendored properly as well.
