### ISSUE TITLE
Fix flakiness of engine tests

### ISSUE THREAD

**Issue by robingustafsson** [loadimpact/k6#469]
There are a couple of test cases for the engine that are flaky. We need to fix them as they generate a lot of false positive CI builds.

The test cases are:
- [`TestEngineRun:collects samples`](https://github.com/loadimpact/k6/blob/master/core/engine_test.go#L233): this test has two wrong assumptions. The first is that the `cutoff` in core/local/local.go will be set before the `ctx` is signalled Done resulting in the second sample to be appended to the `samples` slice in the mocked "RunOnce()" function (basically a race condition). The second is that `<-ctx.Done()` will be selected before `case samples := <-vuOut` in core/local/local.go:Run() which is not always the case (non-determinism of `select`), and can cause all samples from the mocked "RunOnce()" function to be accepted. When either of these two happens there's a "wrong number of samples" error being generated.
- [`TestEngineCollector`](https://github.com/loadimpact/k6/blob/master/core/engine_test.go#L284): There seems to be a race condition here, the test sometimes errors out with a "panic: attempted to collect while not running" (from Dummy collector).

Beyond these two, CircleCI builds also fail sometimes when running tests dependent on external sites like httpbin.org, see https://github.com/loadimpact/k6/issues/464.

**Comment by robingustafsson** [comment]
First one (`TestEngineRun:collects samples`) fixed in https://github.com/loadimpact/k6/commit/48f2c407283988b242e5d5e55416826b19ce213c

**Comment by antekresic** [comment]
How about using this replace httpbin.org dependencies? 
https://github.com/ahmetb/go-httpbin

Or maybe just keep it simple and use httptest package?

**Comment by antekresic** [comment]
@robingustafsson it seems everything from this issue has been taken care of except the [TestEngineCollector](https://github.com/loadimpact/k6/blob/master/core/engine_test.go#L284) test. I have encountered this issue yesterday and it seems the issue is in how the [Collect](https://github.com/loadimpact/k6/blob/master/stats/dummy/collector.go#L54) function is implemented in the [test Collector](https://github.com/loadimpact/k6/blob/master/stats/dummy/collector.go#L31). There is a [check](https://github.com/loadimpact/k6/blob/master/stats/dummy/collector.go#L58) for the running flag which is inconsistent with other [Collector](https://github.com/loadimpact/k6/blob/master/lib/collector.go#L31) implementations since they don't do such a thing. 

I guess we have to sync up the test with actual Collector implementations in order to get this sorted out. I'm willing to do take care of this one once we agree on the solution here.

**Comment by na--** [comment]
Just making a note here that in https://github.com/loadimpact/k6/pull/553 we discussed that the dummy collector has to be refactored, probably it should use a `Sample` channel instead of a slice. When the context channel is closed, `Run()` can close the `Samples` channel and exit, all following `Collect()` calls will panic - just like the current behaviour, but better :)
