### ISSUE TITLE
High CPU usage of K6 on high bandwidth usage.

### ISSUE THREAD

**Issue by FournierAlexandre** [loadimpact/k6#477]
Hello,

I have a setup with a server that have several network 10 gig card.  I did a quick and dirty modification to hardcode support for multiple NIC and try to reach a 30 Gig download from our server just to bench K6 on how well he is doing for vertical scaling.

First, the maximum bandwidth K6 was able to get is around 24 but not steady (with 10 VUS on each card).  The machine was using around 50%-60% for a 24 core machine with 10 Gig or RAM.  We have a in-house tools that is able to reach the full bandwidth with 9% only.

Our setup : 

**Machine where K6 is run :**
- Windows 10 machine
- 3 X 10 Gig NIC
- 64 GB RAM
- 24 CPU
- Server and Client are connected on the same switch (no unecessary rooting)

**K6 configuration**
- 30 VUS (10 on each card) ==> increasing does not change anything on Bandwidth but increase CPU
- Simple JS Script that only do a HTTP GET
- 60 second test.

Do you have any idea where the CPU is used for?  Are the files download are written on disk on in RAM?

Thanks!

**Comment by robingustafsson** [comment]
Hi @FournierAlexandre! Thanks for creating the issue. I don't have a definitive answer as to why you're seeing the performance you're seeing, I need to do some profiling first. But I'd say, given your description, it's likely related to how we handle incoming data. We save all incoming data in memory (to make it accessible in JS via the `body` response object property). Unless you're using the JSON output option we avoid direct disk access in k6 during test execution.

We haven't spent much time optimizing k6 yet, it's part of the work that will lead to a 1.0 release. One thing we should consider is to have a per-request option to discard incoming data as soon as it's received (this could be "discard all" or by `Content-Type` perhaps, to discard binary but keep textual for example) with the downside that the response body data would not be available to JS (`res.body` etc.)

**Comment by FournierAlexandre** [comment]
Hi  @robingustafsson, thanks for your answer!  These are good lead to understand what is going on.  Do you have a roadmap of what you guys are planning to deliver for 1.0?

**Comment by robingustafsson** [comment]
@FournierAlexandre Yes, we'll be sharing our roadmap for 1.0 and beyond on Github in the next week or so.

**Comment by na--** [comment]
I'll close this issue because we've had a lot of changes since it was created:
- [`discardResponseBodies`](https://k6.io/docs/using-k6/options#discard-response-bodies) and [`responseType: 'none'`](https://k6.io/docs/javascript-api/k6-http/params), to make k6 not save response bodies in memory, since [k6 v0.23.0](https://github.com/loadimpact/k6/blob/master/release%20notes/v0.23.0.md#k6http-new-options-to-discard-the-response-body-or-to-specify-its-type-742-and-749)
- [`--compatibility-mode=base`](https://k6.io/docs/using-k6/javascript-compatibility-mode), a way to skip babel transformation and core.js in every VU, since [k6 v0.26.0](https://github.com/loadimpact/k6/blob/master/release%20notes/v0.26.0.md#a-new-javascript-compatibility-mode-option-1206)
- [dedicated executors](https://k6.io/docs/using-k6/scenarios/executors) and a refactoring of the previous execution engine that essentially had `sleep(1ms) and check what needs to be done` scheduling :sweat_smile: in [k6 v0.27.0](https://github.com/loadimpact/k6/blob/master/release%20notes/v0.27.0.md#new-execution-engine-1007)
- native multi-NIC support via the [`localIPs` option](https://k6.io/docs/using-k6/options#local-ips) since [k6 v0.29.0](https://github.com/loadimpact/k6/blob/master/release%20notes/v0.29.0.md#support-for-setting-local-ips-potentially-from-multiple-nics-1682)
- a ton of other changes that might have affected network throughput and CPU usage one way or the other

So, I am not claiming there aren't any performance issues anymore, I am sure there are plenty, but they need their own issues :smile:
