### ISSUE TITLE
parse errors

### ISSUE THREAD

**Issue by masihtehrani** [loadimpact/k6#511]
hello
i have code check api
```
check(res[0], {
                "is status 200": (r) => r.status === 200,
            "is id exist in data ": (r) => Number.isInteger(a[0].id),
            "is title exist in data ": (r) => typeof a[0].title == 'string',
            "is name exist in data ": (r) => typeof a[0].name == 'string',
            "is shopName exist in data ": (r) => typeof a[0].shopName == 'string',
            "is productName exist in data ": (r) => typeof a[0].productName == 'string'
```
and k6 print error in terminal
<img width="1059" alt="screen shot 1396-12-02 at 13 05 11" src="https://user-images.githubusercontent.com/9476972/36473003-93e7dec4-1708-11e8-9d45-ead1451af420.png">

`
✗ is status 200
     ↳  0% — ✓ 0 / ✗ 1
`
but not show any error in grafana & error is empty and just show request per second
<img width="1441" alt="screen shot 1396-12-02 at 13 08 24" src="https://user-images.githubusercontent.com/9476972/36473019-9caad41c-1708-11e8-99f7-7ef01e411a1e.png">

**Comment by robingustafsson** [comment]
Sorry, meant `checks` measurement not `errors`. Looking at your screenshot from Grafana again now, it looks like it has picked up that there's a "is status 200" check. I got the two metrics confused for a moment there 😄, the "Errors per second" is not going to display check errors, it's meant to represent JS runtime errors/exceptions (the `errors` metric from k6).

**Comment by masihtehrani** [comment]
@robingustafsson how can get error, i needed set alarm in grafana when have problem in api.
i replace error with check an my code is not working

**Comment by na--** [comment]
@masihtehrani, sorry not responding here before, hopefully you've found a solution in the meantime. 

But just in case, to explain what @robingustafsson meant, I'll use an example with the following simple test script:
```js
import http from "k6/http";
import { check } from "k6";

export default function (data) {
    let resp = http.get("https://test.loadimpact.com");
    check(resp, {
        "status is 200": (r) => r.status === 200,
        "content is present": (r) => r.body.indexOf("blah") !== -1,
    });
}
```

The `status is 200` check should succeed, while the the `content is present` should fail, since that page doesn't have `blah` in it's body. I'll use the JSON output instead of the InfluxDB one for an easier demonstration, but the metrics data would be the same in either case. So if you save the above script as `script.js` and run `k6 -o json script.js`, you'd get something like this in the output:
```js
// ... 
{"type":"Point","data":{"value":1,"tags":{"check":"status is 200","group":""},"time":"..."},"metric":"checks"}
{"type":"Point","data":{"value":0,"tags":{"check":"content is present","group":""},"time":"..."},"metric":"checks"}
// ... 
```
As you can see, you should be able to filter by those `tags` in InfluxDB and Grafana and visualize whatever you need. I'll close this issue for now, but feel free to reopen it or [contact us in slack](https://k6.io/slack/) if you think there's a bug in k6.
