### ISSUE TITLE
Homogenize k6 timestamp format to a strict, fixed form

### ISSUE THREAD

**Issue by Griatch** [loadimpact/k6#513]
Currently the metric data comes out with a time stamp on a few possible forms depending on time zone and number of valid nanosecond digits. For optimization in parsing (e.g. on the LoadImpact side) it would be better if a single, fixed format was enforced. This is the desired format: 

`'2017-12-05T11:58:30.909653069+01:00'`

Some examples of other forms `k6` currently outputs:  

`'2018-02-22T20:29:56.4673Z'` (should be `'2018-02-22T20:29:56.467300000+00:00'`)
`'2018-02-22T20:29:56.4'` (should be `'2018-02-22T20:29:56.400000000+00:00'`)

Maybe there are other possible forms. For efficient parsing it would be good if there was no uncertainty.

**Comment by na--** [comment]
I think we should just use nanosecond unix timestamps (e.g. `1520590442828524119`)  instead of string-based date-times. This should both save space when streaming the results to the cloud and remove the need for [complicated parsing](https://github.com/loadimpact/k6-lib/pull/22/files#diff-40b061090eff84ade664e0167caa864aR92) of the data.

**Comment by na--** [comment]
Considering that large integer numbers tend to be [automatically rounded](https://stackoverflow.com/questions/1379934/large-numbers-erroneously-rounded-in-javascript) in JavaScript because they're not real integers, I think that I'll have to pass the microsecond timestamps as a string in the JSON, just to be safe, even if Python doesn't have the same issues.
