### ISSUE TITLE
open function should be available from within the setup() (and teardown() calls)

### ISSUE THREAD

**Issue by vtanakas** [loadimpact/k6#557]
Having local initialization data (i.e. files on disk) accessed from the script outside of any function call, while remote initialization data (results from http/ws queries) is performed in setup() results in code that executes the same number of times: once, at essentially the same point in code: before default(), being placed in two different locations: outside the setup() call, vs inside the setup call.

```
my_local_data = JSON.parse(open("local_data.json")); // Must be called from the script outside of a setup() as open() is only available in an init context.

export function setup() {
    let remote_data = http.get("http://my.configserver.com").json();
    return { "data": [my_local_data, remote_data];
}

export function default(global_data) {
   // Tests make use of data from both local store and remote store.
}

export function cleanup(global_data) {
   // cleanup global data...
   cleanup_local_data(global_data["data"][0]); // or cleanup_local_data(my_local_data), etc...?
   cleanup_remote_data(global_data["data"][1]);
}
```

**Comment by robingustafsson** [comment]
I do understand this perceived discrepancy in the API here, but there's a reason behind it :)

It boils down to our design goal to support single machine and clustered/distributed (whether that'd be self-managed clustering or using the Load Impact cloud service) execution without requiring changes to test scripts to move between these execution modes.

By restricting the `open()` call to only be available in "init code" (https://docs.k6.io/docs#section-init-and-vu-stages) we can easily determine what local files are needed to run the test and thus what we need to bundle up when distributing the test to multiple nodes in a clustered/distributed test (where we make use of the equivalent of running `k6 archive script.js` to package up the JS code and all dependent resources into a tar file).

This is also why we restrict HTTP calls in "init code", to "force" test code to be inside the `default function` and now (since v0.20.0) also in `setup`/`teardown`.

**Comment by luizbafilho** [comment]
documented that here: https://dash.readme.io/project/k6/v1.0/docs/open-filepath-mode

**Comment by toshovski** [comment]
I'm writing some file-upload tests for the past two days and this restriction really hurts. I want to have a big set of files, which I want to upload, but I cannot do it dynamically. I have to define each file in the code. What I really want, is to iterate over those files in a directory and upload and run checks after each upload. So if you enable the function open to open directory and give me the list of the files, It will solve that issue. On the other hand you can deploy the whole directory to the cluster

Right now I execute k6 per file and iterate over the files in a bash script, but I don't feel this is the right solution. I cannot execute in a parallel and upload multiple files at the same time. And open() is essential for uploading files. Alternative I'm thinking about uploading those files somewhere and use the http.get() endpoint. This is more infrastructure work, but should work.

**Comment by na--** [comment]
@toshovski, as I've mentioned in [your forum question](https://community.k6.io/t/allow-opening-folders-with-the-open-function/104), the rationale for @robingustafsson's answer above hasn't changed and we don't plan to lift the restrictions of using `open()` only in the init context for now. But we definitely want to improve the uses experience of working with files, as I hope is clear from the [new issue](https://github.com/loadimpact/k6/issues/1005) and the other ones linked in it.

I'm just commenting here to point any users that may stumble on this issue in the future towards the newer issues and discussions, since a closed year-old issue isn't the best place to have this conversation... :smile:
