### ISSUE TITLE
Make setup setUp timeout  configurable via a variable

### ISSUE THREAD

**Issue by sri85** [loadimpact/k6#576]
As part of our performance tests we create a lot of data before we begin the actual load test   . This test data generation script(which is again a k6 script) was run prior to the test.

With the introduction of `setUp` and `tearDown` we moved the test data generation script to `setUp` method to make it more cleaner and concise . We are now seeing errors engine timing our tests out as the `setUp` takes more than 10 seconds  and from the source code it looks like we are running into 
https://github.com/loadimpact/k6/blob/master/core/local/local.go#L141 where the time is hardcoded to 10 seconds.

Can we please make this timeout configurable via a variable ?

**Comment by na--** [comment]
Thanks for mentioning this, [we were aware](https://github.com/loadimpact/k6/issues/539#issuecomment-373733101), but it probably deserves its own issue. We definitely plan to fix this soon! The `setup` and `teardown` were merged with some unpolished edges like this because we wanted to make them available in the previous release, due to popular demand by a lot of users.
