### ISSUE TITLE
k6 vus limitation

### ISSUE THREAD

**Issue by MaxVinogradov** [loadimpact/k6#577]
Does k6 have any limitation regarding to the vus count?
If my vus is 

`vus: 1007500`

 - will it work correctly?

**Comment by na--** [comment]
There is no artificial limit imposed on the number of virtual users, though in your case I doubt you'll easily find a machine that would be able to run that many VUs simultaneously. That's because each VU runs in its own [goroutine](https://tour.golang.org/concurrency/1) and has it's own [goja](https://github.com/dop251/goja) JavaScript runtime and other assorted helpers. Are you sure you need that many **simultaneous** actual virtual users and not iterations or requests? Take a look [here](https://docs.k6.io/docs/running-k6) and at the `--iterations` description [here](https://docs.k6.io/docs/options) and `http.batch()` documentation [here](https://docs.k6.io/docs/batch-requests) for more information.

I'm closing this issue for now because I think that the `#support` or `#feedback` channels in the [k6 slack](https://k6.io/slack/) may be a more appropriate place for this type of discussion.
