### ISSUE TITLE
Give example in docs how to only launch a certain group of requests

### ISSUE THREAD

**Issue by mNachUbi** [loadimpact/k6#584]
I don't know if I'm reading the k6's group feature, or the loadtest objective correctly so feel free to correct me but :

Since we already have a grouping feature for the results, I think it would be nice if we could specify (via arguments?) that we want to launch only a group or a certain groups of requests.

**Comment by na--** [comment]
You could easily do this now with existing k6 features and low overhead, so I'm not sure if it's worth it to implement something new specifically for this. 

You can pass which groups are enabled for a run via [environment variables](https://docs.k6.io/docs/environment-variables) and create a small wrapper function around the built-in `group()` that checks if that particular group is enabled for the specific run, something like this:
```js
function mgroup(name, fn) {
 if (__ENV[name + "_enabled"]) {
   return group(name, fn);
 }
}
```
Please comment if you think that this is insufficient or if there's a good reason to implement something custom in k6 itself to handle such cases. Otherwise I'm leaning towards closing this issue or maybe using it as a reason to improve our documentation and mention this example, instead of for writing new code.

**Comment by mNachUbi** [comment]
That sound good to me, the case is pretty specific and the implementation is light enough that it doesn't require writing new code.I'll implement your suggestion in my code thank you for your feedback.

**Comment by na--** [comment]
This feature was made much easier with `scenarios` in the k6 v0.27.0 release: https://github.com/loadimpact/k6/releases/tag/v0.27.0
And they were reasonably thoroughly documented in https://k6.io/docs/using-k6/scenarios, so that and https://k6.io/docs/using-k6/environment-variables should be enough to close this
