### ISSUE TITLE
Test summary accessible inside the teardown function

### ISSUE THREAD

**Issue by zypherman** [loadimpact/k6#647]
It would be really helpful to allow access to the entire test summary inside the teardown function. There is a lot of helpful information that is inside the summary that is written to the console after the test shuts down. If you could grab onto that inside the teardown function it would make reporting a lot easier.

**Comment by na--** [comment]
I agree, this would be helpful in some use cases, but like I mentioned in the [slack chat about it](https://k6io.slack.com/archives/C3E688J8Z/p1523409003000113), I'm not sure how easy it would be to implement with the cloud/cluster execution. Most of the summary stats (basically any `Trend`s, where we calculate things like `p(90)`) are not easily merge-able in a distributed execution scenario, so we probably have to haul a lot of raw data between nodes.

**Comment by na--** [comment]
Related issues: https://github.com/loadimpact/k6/issues/351 and https://github.com/loadimpact/k6/issues/355

**Comment by na--** [comment]
To tie things up here, this is now closed by https://github.com/loadimpact/k6/pull/1768. As you can see from the PR, the summary is not accessible from inside of `teardown()`, mostly because `teardown()` can produce metrics that affect the summary, and because `teardown()` works in the cloud and this new feature isn't yet supported there. So, instead, this can be achieved by exporting a function called `handleSummary()`.
