### ISSUE TITLE
cloud requires 'target' in stages, conflicting with docs

### ISSUE THREAD

**Issue by countergram** [loadimpact/k6#648]
Documentation of 'options' contains the following stages:

```
stages: [
    { duration: "1m", target: 10 },
    { duration: "1m" },
    { duration: "1m", target: 0 }
  ],
```

However, `k6 cloud` throws this error:

`ERRO[0001] 2 Invalid value for stages.1.target: None is not of type 'number'`

**Comment by luizbafilho** [comment]
@robingustafsson this validation is coming from the cloud API. `k6` itself allows empty target.

**Comment by na--** [comment]
Yep, that's why I tagged it as cloud :smile: Looking at this again, I'm not sure we should actually fix it and allow `target` to be omitted. It may save a few seconds for users, but it unnecessarily adds more confusion about how stages work. That would be especially bad once we add the [arrival-rate based execution](https://github.com/loadimpact/k6/issues/550) and/or some other execution mode like the log-based one. Or when we add different non-linear ramp-up/ramp-down strategies.

I feel like in this particular case, explicitness should trump conciseness and we should just edit the docs so we don't advertise support for this.

**Comment by luizbafilho** [comment]
Added the target to every place that used stages in the documentation.
