### ISSUE TITLE
 TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by vivikenen** [loadimpact/k6#653]
Hi, 

I've tried to use the K6 to run the performance testing.

Here is the code:
![wechatimg78](https://user-images.githubusercontent.com/11569400/40594498-e08f6fca-6272-11e8-883f-ed98b03639b2.jpeg)

If I setup the target value < 50, everything works fine. The `[0]` is not undefined. 

But if I setup the target value > 50 (like 60), it throw the error shown as below: 
![wechatimg79](https://user-images.githubusercontent.com/11569400/40594479-c21fc724-6272-11e8-8059-e9b7fa7e5db5.jpeg)
（Not All vus call throw this error, 94% has been successful proccessed. )

Here is the stages option:
```
export let options = {
   stages: [
    // Ramp-up from 1 to 5 VUs in 10s
     { duration: "20s", target: 60 },

       // Stay at rest on 5 VUs for 5s
      { duration: "30s" },

      // Ramp-down from 5 to 0 VUs for 5s
       { duration: "20s", target: 0 }

   ]
};
```

Just wondering is there anything I missed? Or just the api cannot process that amount of user?

I appreciate if anyone could give some advice

**Comment by na--** [comment]
Maybe there's some rate limiting from the target machine? Do all `status is 200` checks pass? In any case, I'd suggest print-debugging the issue, something like:
```js
// ...
"dump strange responses": (r) => {
  let resp = r.json();
  if (!resp.data || !resp.data[0]) {
    console.log(r.status);
    console.log(r.body);
  }
},
// ...
```

Relying that `r.json().data[0].id` exists is making a lot of assumptions:
- the request returned a non-error response
- that response is a valid json
- that json has a `data` field
- that field is an array and has at least one element
- that element is an object and has an `id` field

If some of those assumptions are not correct some of the time, it will break. When you're load testing a system, it's entirely possible for it to sometimes respond with errors or not respond at all.

Since this doesn't seem to be a bug in k6 itself, I'll close the issue. This type of discussion is more suitable for the #support [k6 slack](https://k6.io/slack/) channel or [maybe stackoverflow](https://github.com/loadimpact/k6#need-help-or-want-to-contribute). Free to reopen the issue or open a new one though, if after debugging this you find out it's actually due to a bug in k6.

**Comment by vivikenen** [comment]
Thx for your kindly reply. 
I've print the debug log successfully.

Just wondering, if I have multiple group action in the same file, are they executed in order?

**Comment by na--** [comment]
Yes, for ease of use the JS code executed in a single k6 VU is (mostly) synchronous. And as I said, such questions are more suited for the `#support` channel in the k6 slack.
