### ISSUE TITLE
how to read the max vus in script

### ISSUE THREAD

**Issue by gushengyuan** [loadimpact/k6#657]
When I run k6 in command line "k6 -u 60 -d 20s run test.js", how could I read the max vus value "60" in my test.js script, and this value is changed very frequent and I don't want to modify the options in script before every running.

**Comment by na--** [comment]
Unfortunately we don't expose the consolidated options back into the script, i.e. if you set/override the number of VUs with a CLI parameter like you do, there's no way to directly read that new value from the script.

There's an [open issue for this functionality](https://github.com/loadimpact/k6/issues/613) and it is something that we'll probably soon fix, but for now you'll have to use a workaround. If you set the number of VUs with an environment variable, you can reference it both in the exported options and in the script. Something like this:
```js
export let options = {
    vus: __ENV.maxvus,
    iterations: __ENV.maxvus
};
export default function () {
    console.log("Running VU #" + __VU + " out of " + __ENV.maxvus);
}
```

If you run it with `k6 run -e maxvus=5 myscript.js`, you'd get something like:
```
INFO[0000] Running VU #5 out of 5                       
INFO[0000] Running VU #2 out of 5                       
INFO[0000] Running VU #4 out of 5                       
INFO[0000] Running VU #1 out of 5                       
INFO[0000] Running VU #3 out of 5  
```

I'll close this issue, since I think it's mostly covered by https://github.com/loadimpact/k6/issues/613 - follow it if you want to know when we fix it.

**Comment by gushengyuan** [comment]
Thanks @na--
