### ISSUE TITLE
Write files

### ISSUE THREAD

**Issue by if-kenn** [loadimpact/k6#666]
I am trying to determine why certain login tests are failing. To do so I need to examine the HTML that has been returned. While I realize that I can output this to the screen via console.log, it is cleaner and easier to read if it is output to a file. Is there anyway to write to the filesystem with k6?

Thanks

**Comment by na--** [comment]
Unfortunately there's no way to write directly to the filesystem. That's mostly because of security and portability concerns when dealing with the distributed cluster and cloud execution.

For easier debugging, we [recently added](https://github.com/loadimpact/k6/pull/634) a `--logformat=raw` option that doesn't output debug information in the logs. If you run `k6 run --logformat=raw script.js 2> debug.html`, you'd get only the things you output via `console.log()` in the newly created `debug.html`

**Comment by if-kenn** [comment]
Thanks for the reply, I will look towards that for debugging. I guess I could also setup a collector server to record html/data as well.

**Comment by na--** [comment]
Yes, it would probably be easier for debugging more complicated scenarios. Another possibility is passing things through `JSON.stringify()` before logging them and then parsing the resulting log with something like `jq`.

**Comment by na--** [comment]
Closing this for now, since we don't currently plan to introduce support for writing files or other potentially unsafe operations. Logging with the `--logformat=raw` and `--logformat=json` options and the `--httpdebug` flag should cover most debug needs, though we can potentially reopen this issue if there's enough user demand and we decide to add some unsafe local debug execution mode in the future.

**Comment by ofauchon** [comment]
Why not adding a --unsafe-operations flags in k6 for such cases ?

Writing raw files can be useful eg: when you want them to be consumed by an existing process (which expects a specific format) 

Implementing a companion http server for that should work, but introduce extra overhead. 

Olivier

**Comment by na--** [comment]
@ofauchon, we now have xk6, so you can write unsafe extensions in Go that do pretty much anything, including write files. More details: 
- https://github.com/k6io/xk6
- https://k6.io/blog/extending-k6-with-xk6

It's a bit more involved, but at the same time it's much more flexible than what you suggest. It allows you to do anything, from writing files to apparently [connecting to minecraft servers](https://github.com/ForgottenWorld/xk6-minecraft) :sweat_smile:

**Comment by nguyenquangtay** [comment]
Hello, 
I'm a newbie on K6,
I'm facing a problem with saving the cookie to a local file then re-use it for calling another APIs...
after searching, I found this, but I don't know how to use it, so anyone could help me using the xk6 for writing the cookie to local file, thank you so much!
