### ISSUE TITLE
Using k6 with socket.io

### ISSUE THREAD

**Issue by euclid1990** [loadimpact/k6#667]
Have anyone used k6 with socket.io library ?
I have nodejs server using socket.io, so when I using following code to test my websoket:

```js
import ws from "k6/ws";
import { check } from "k6";

export default function() {
  var url = "wss://localhost/socket.io";

  var res = ws.connect(url, function(socket) {
    socket.on('open', function() {
      console.log('connected');
    });
    socket.on('close', function() {
      console.log('disconnected');
    });
  });

  check(res, { "status is 101": (r) => r && r.status === 101 });
}
```
It output ` GoError: websocket: bad handshake` because my node server not using normal websocket, it using https://socket.io/

Then I try include https://www.npmjs.com/package/socket.io-client into`script.js`

```js
import socketio from './socket.io.js';
...
socketio.io("wss://localhost/socket.io");
```

It output error `TypeError: Cannot read property 'Buffer' of undefined at /vagrant/shared/socket.io.js:6:8072(15)`. It seem k6 javascript compile not have `global` variable.

Can anyone help me ! Thank you.

**Comment by na--** [comment]
You cannot directly run Node modules in k6 because they often depend on parts of the NodeJS standard library. In this case, it seems like socket.io needs [`Buffer`](https://nodejs.org/api/buffer.html).

What you can sometimes do to use **some** of those modules in k6 is to pass them through [browserify](http://browserify.org/) or use their pre-built versions meant for browsers. Take a look at the [k6 documentation that describes this](https://docs.k6.io/docs/modules#section-npm-modules). I'm not sure if the socket.io client would work that way, but since it heavily depends on network access, there's a good chance that it won't, sorry. 

I'm not very familiar with socket.io, but maybe the [native k6 websockets](https://docs.k6.io/docs/websockets) would be sufficient? If not, you may have to wait until k6 has better compatibility with JS libraries or until we have native support for it.

**Comment by euclid1990** [comment]
@na-- Thank you, I will try it tommorow :(

**Comment by euclid1990** [comment]
Finally, I decided to use [Artillery](https://artillery.io/) for testing with `Socket.io` 😂

**Comment by XEmAX32** [comment]
Hi!
I recently published a k6 extension to add socket.io support, there's already something minimal that you can find [here](https://github.com/XEmAX32/xk6-socket.io).

Currently supports:

emit/send
listen to custom events
listen to connect/disconnect
it's a wrapper around k6 ws implementation so all other methods are exported from there.
