### ISSUE TITLE
It seems the K6_CLOUD_HOST env vars is not honored with "k6 login cloud"

### ISSUE THREAD

**Issue by robingustafsson** [loadimpact/k6#695]
When testing `k6 login cloud` against internal dev and staging systems @Griatch and I discovered that it doesn't seem like the `K6_CLOUD_HOST` env var is being honored by k6. It seemed to send all requests to the default production URL [1].

[1] - https://github.com/loadimpact/k6/blob/master/stats/cloud/config.go#L92

**Comment by na--** [comment]
This seems relatively easy to fix, but it will lead to probably unintended consequences. Every successful call to `k6 login cloud` (or `k6 login influxdb` for that matter) ends with [`writeDiskConfig()`](https://github.com/loadimpact/k6/blob/b86aa28140a8ca5137cc60c0346af10163df822b/cmd/login_cloud.go#L106)... So that means that if k6 honors environment variables for `k6 login` commands and you use something else for `K6_CLOUD_HOST` just once, that value will be saved in the config as well. So that saved cloud host URL would be used from then on unless you overwrite it again with something else.

**Comment by Griatch** [comment]
@na-- I personally never liked this automatic config-updating that `k6` does. Editing the config file (changing the default) should only happen on a conscious operation and not not whenever setting an env variable like this. It's really confusing. 

I guess this is a matter of policy, but I'd say that *at least* the user should be asked if they want to update the settings file instead of silently auto-changing it. Maybe even avoid changing anything (except very first setup, maybe) unless you do `k6 saveconfig` (or something) to explicitly save the current settings as default ...

**Comment by na--** [comment]
I wouldn't want a multi-step process, but I'd say that the `k6 login` command should only change what the users expect it to change. So `k6 login influxdb` should only modify the influxdb settings in the config (without touching anything else), `k6 login cloud` and `k6 login cloud -t` likewise would only modify the loadimpact section. 

So implementation-wise, we probably have to "build" 2 different configs - one for the actual k6 operation that's behaves like the `k6 run`, `k6 cloud`, etc. configs (i.e. is also affected by environment variables). The other one would be just the existing global file config to which we'll apply the new login settings and which we'll save back to the file system without any other additions. I think this wouldn't break user expectations about UX and would also allow us to modify `K6_CLOUD_HOST` and other variables for testing.
