### ISSUE TITLE
Check for a request made to another endpoint

### ISSUE THREAD

**Issue by cesarvarela** [loadimpact/k6#718]
HI, I'm stress testing a messenger bot, and would like to know if there is a way to use k6 for it.

It works as follows:

The bot exposes a webhook at let's say: `facebook/webhook` that receives POST requests for every message the bot receives and answers those immediately with a `200 OK`. Then, the bot responds by making  a POST to a Messenger platform endpoint: `http://graph.facebook.com/*/messages`.

I need to stress test the entire flow, would like to know if this is possible with k6

**Comment by na--** [comment]
I'm not familiar with the the Facebook API, but as long as you have some some way to track when the message was actually sent, you can use a [k6 custom metric](https://docs.k6.io/docs/result-metrics#section-custom-metrics) to track it. How you get that information probably very much depends on your messenger bot and may require modifications in it to make it more testable. When you simply immediately return a `200 OK`, there's no way for an outside observer like k6 to know how long it took to process the message...

I'll close this issue for now, since the [k6 slack channel](https://k6.io/slack/) or [stackoverflow](https://github.com/loadimpact/k6#need-help-or-want-to-contribute) are much better places to discuss something like this. Feel free to reopen the issue or open a new one if you want a specific new feature in k6 that could help you with this or if you find a bug.

**Comment by peterbozso** [comment]
For other people stumbling into this issue, I created a topic on the community forum: https://community.k6.io/t/testing-webhooks/1138
