### ISSUE TITLE
Unexpected DNS caching

### ISSUE THREAD

**Issue by paulgrav** [loadimpact/k6#726]
I’d better like to understand K6s behaviour in relation to DNS caching.

I’m trying to run tests against a couple of load balanced K8S clusters. The failover is managed by a traffic manager so once the traffic manager has detected a failure in one of the clusters it will update the DNS records so that traffic only hits the healthy cluster. I’ve tried to reduce the problem, described below.

# Steps to reproduce:

1. Create a performance test to run for 5m against a particular endpoint. E.g., https://gist.github.com/paulgrav/a8b6d77639b0d54774b499c5dfd660c6
2. Ensure that `host.name` points to a CNAME that returns HTML and has a TTL of 60s.
3. Run the test.
4. After one minute, update the CNAME for `host.name` to a domain that doesn’t resolve e.g., `foo.bar.asdf`

# Actual results:

All HTTP calls in the test succeed despite the CNAME record being changed to point to a domain that doesn’t resolve.

# Expected results:

After 60s but before the test ends, there should be some test failures because the HTTP requests fail.

**Comment by luizbafilho** [comment]
Hi @paulgrav,

That is expected, we cache the DNS records for the whole period of the test in order to maximize the throughput. https://github.com/loadimpact/k6/blob/9531175bc4f5b525655db6c8f96865689bb215e7/lib/netext/dialer.go#L54


I guess it would be nice to have an option to set the DNS caching time, what do you think @na-- ?

**Comment by paulgrav** [comment]
Thanks for acknowledging this. Respecting the TTL would be ideal. Overriding the DNS caching via envvar would be better than the current hardcoded indefinite cache time.

**Comment by bookmoons** [comment]
Looking into what it would take to do this.

Here's the situation:
* Stdlib doesn't expose TTL.
* I'm not finding a ready made caching resolver that respects TTL.

I propose to handle this by adding TTL support to an existing quality package then replacing the current resolver with that package.

[`domainr/dnsr`](https://github.com/domainr/dnsr) seems to be the nicest. It has caching. It's well tested. It throws meaningful errors. The team [is receptive](https://github.com/domainr/dnsr/issues/31). Don't think it will be hard to add.

**Comment by na--** [comment]
I'm not familiar with [`domainr/dnsr`](https://github.com/domainr/dnsr), but at a first glance, I don't see any issues with using it, if it had TTL support added. It depends on the [`miekg/dns`](https://github.com/miekg/dns) DNS library, which is probably what will be using to implement https://github.com/loadimpact/k6/issues/851 and https://github.com/loadimpact/k6/issues/1011 anyway.

**Comment by bookmoons** [comment]
OK, perfect.

**Comment by bookmoons** [comment]
Started a submission to `dnsr` domainr/dnsr#32 to add TTL support.

**Comment by bookmoons** [comment]
The `dnsr` team has kindly accepted the patch. Got it on my list to put together a k6 patch trying it as a replacement resolver.

**Comment by bookmoons** [comment]
Realized something else is necessary. I have a question in with `dnsr` domainr/dnsr#35 about a second patch.

**Comment by bookmoons** [comment]
I'm not hearing back from dnsr. They have their own efforts taking attention.

What would you guys think about forking dnsr and publishing a loadimpact resolver? There does seem to be a need for it. Had trouble finding a decent one when I did that search. The license is MIT.

I have a tested patch for this final feature ready to submit.

**Comment by na--** [comment]
I'd prefer that we avoid forking a project that's at least somewhat active... Given the way Go imports are specified by URLs, it's a bit of a PITA to temporarily fork a repo. I'm not sure if it would be better after https://github.com/loadimpact/k6/issues/1070, but for now it's probably not worth it. 

I haven't delved into the dnsr code or your patches there yet, but does your latest patch need to be in the repo itself? Can it work as a helper function in the k6 repo as a temporary workaround?

**Comment by bookmoons** [comment]
Alright. I'll try pinging dnsr, maybe they just haven't seen it.

Tried to find something external first, but I don't think there's a way. It needs to use cache in a new way. The cache field is private so (I think?) there's no way to get at it from outside.

**Comment by bookmoons** [comment]
Opened a preliminary submission for this #1085. Turned out there are a few things dnsr doesn't quite do. I've built around it to try to handle them. It puts more resolution logic outside the resolver than I really wanted. Won't blame you if you don't want it. But at least it gives you the option. Maybe things can be moved into the resolver over time.

**Comment by na--** [comment]
Thanks! I'll take a thorough look tomorrow or early next week.

**Comment by gabrielqs** [comment]
Hi! Would this by any chance be available on 0.26? I'm experiencing it on a round-robin internal domain managed by route 53, TTLs aren't respected to a single node ends receiving all of the traffic from k6.

**Comment by na--** [comment]
@gabrielqs, sorry for the late response :disappointed: Unfortunately these fixes won't be in k6 v0.26.0, since we're in the final stages of testing and hoping to publicly release it by the end of this week. We're aiming to have all of the DNS fixes be part of the next k6 release though, so watch this space for updates! For context, the delay with fixing the DNS issues stems from the lack of suitable DNS resolving and caching libraries for our use cases in k6, so we basically had to write one, starting from a lower-level than expected...

**Comment by gabrielqs** [comment]
@na-- thanks for the info!

**Comment by sniku** [comment]
I have an interesting observation regarding DNS caching. 

When running a large scale test against a system hosted on AWS, the load-balancer will change IPs for the target system during autoscaling.

A "cold" LB will expose only 1 IP. When it detects a large load, it will start auto-scaling and will spin up additional LB machines, and expose additional IPs. The old IP from the "cold" LB will be removed after a while. 

Since k6 cached the original IP and doesn't know about the new IPs, requests will start failing even though the target system isn't overloaded.

![image](https://user-images.githubusercontent.com/442646/80723654-3219c800-8b01-11ea-96c5-00e01aa134d6.png)

Errors like this are printer by k6 on the terminal when it can't connect to the old IP:

```
WARN[0057] Request Failed                                error="Get http://pawel.staging.loadimpact.com/static/logo.svg?url=v3: dial tcp 52.18.24.222:80: i/o timeout"
```

**Comment by imiric** [comment]
While working on #1612 I stumbled upon this project: https://github.com/ncruces/go-dns

It's a very lightweight implementation of custom resolvers that works by overriding `net.DefaultResolver`. If nothing else it could serve as a reference for fixing these DNS issues in k6 with a less radical approach than writing custom resolvers from scratch, something we've made progress on by building on top of https://github.com/miekg/dns, which is a much more complex re-implementation of DNS in Go. The `net.DefaultResolver` approach would be much simpler while continuing to benefit from the stdlib DNS support.

If we need an abstraction for DNS messages, we could also use https://godoc.org/golang.org/x/net/dns/dnsmessage instead of `miekg/dns`. This package is used internally by the stdlib so it makes sense to reuse that in our code rather than bring in a large dependency like `miekg/dns`.
