### ISSUE TITLE
How to get  current date in k6?

### ISSUE THREAD

**Issue by wodepan** [loadimpact/k6#731]
When i post http request,  there is a date field, how can i get current date by k6?
i wrote code :  
    var d = new Date();
    var year = d.GetYear();
and i got errors:
ERRO[0001] TypeError: Object has no member 'GetYear'

**Comment by na--** [comment]
It seems like `getYear()` has been deprecated and is officially unsupported: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getYear

You can use [`getFullYear()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getFullYear) or [`getUTCFullYear()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getUTCFullYear) instead, both of which work in k6.

Closing this issue since it seems like k6 is behaving correctly in this case.

**Comment by wodepan** [comment]
thanks.
