### ISSUE TITLE
What about k6 central controler.

### ISSUE THREAD

**Issue by ofauchon** [loadimpact/k6#733]
Hi. 

According to documentation, k6 scalability is based on docker.
This is great, but it's not enough to fine control performance tests.

What about having a K6 Central Controler that would manage  all k6 
instances to perform centalized actions like:  

- Push/synchronize scripts (not a single .js file, but more a source tree) to all k6 nodes 
- Start/Stop/Pause/RendezVous of k6 scripts and instances
- Manage failover, scale up/down of k6 instances (through docker apis..)
- Execute pre/post-flight scripts and share datas with nodes
- Provide centralized, real time monitoring of  k6 injectors (cli console)
- Provide simple queues or key/value store available for all nodes to share informations.

Olivier

**Comment by na--** [comment]
I wouldn't say that k6's scalability is based on docker and I can't find where we claim that in the docs, but for sure the docker image would be useful if your environment is already fully containerized. And a lot of the container orchestration solutions like kubernetes would provide very nice benefits in terms of easier up/down scaling, connectivity, monitoring, etc. 

But as you correctly mention, for the moment there's no native way to orchestrate and control multiple k6 instances. There's a [REST API](https://docs.k6.io/docs/rest-api) and you can use [archives](https://docs.k6.io/docs/archives-for-bundling-sharing-test) to bundle and distribute source trees in one file, but currently you'd have to write the whole orchestration yourself.

We plan to implement native k6 clustering and distributed execution, but we haven't started working on that yet. [This is the issue](https://github.com/loadimpact/k6/issues/140) that would be used to track those efforts and it's in the end of the [roadmap](https://github.com/loadimpact/k6/wiki/Roadmap) for this year. I'll close this for now, since it'll be referenced in the [original clustering issue](https://github.com/loadimpact/k6/issues/140) and some of the things you listed are actually already implemented (like the API and archive bundles). Monitor the other issue for any updates, since we'll reference it when we start work on this.
