### ISSUE TITLE
FileData: Support of the size parameter in Content Disposition

### ISSUE THREAD

**Issue by shirmanov** [loadimpact/k6#736]
At the moment FIleData supports only the name and filename parameters in content disposition header. It would be great to have an option to specify the size parameter as well. At server side many applications expect it to be sent.

**Comment by na--** [comment]
Thanks for requesting this, but it seems like `size` has been removed in the newest RFC about the `content-disposition` header: https://tools.ietf.org/html/rfc6266#appendix-B. And even if we supported it, I can't think of a use case where you'd have to specify it yourself, instead of having k6 derive it from the length of the supplied `data`.

I'm closing this issue for now, but please reopen it if you think there's a valid use case for the `size` parameter, or simply comment again and give some real-world examples and I'll reopen it.

**Comment by shirmanov** [comment]
Sure, no need to support what is already became deprecated. Thank you.
