### ISSUE TITLE
Cookie check issue (jar & non-jar cookie, potential encoding issue)

### ISSUE THREAD

**Issue by san-ouadghiri** [loadimpact/k6#772]
Here,'s the issue

**Code**
```
import { group, check, sleep } from 'k6';
import http from 'k6/http';

export default function() {

	//Cookie Jar (per-VU)
    let jar = http.cookieJar();
    jar.set("https://sso.hubside-preprod.com", "mycookie", "hello world");

	group("SSO call", function() {
		let res;
		res = http.get("https://sso.ourdomain.com/stuff",
			{
				"cookies": {
				"cookieilike": "q1epul507"

			},
			"headers": {
					"Host": "https://sso.ourdomain.com",
					"User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0",
					"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
					//Bunch of headers
				}
			}
		);
		check(res, {
			"status is 200": (r) => r.status === 200,
			//"cookie has jar value": (r) => r.json().cookies.mycookie === "hello world"
                        //"cookie": (r) => r.json().cookies.PHPSESSID === "plop"
		});
	});
}
```

Status check alone is ok (fails if not 200, pass if 200). However: 
1 - if I uncomment any of the 2 cookie checks, I get an error (see below)
2 - the cookie checks always pass, whatever value they check
3 - if I activate the debug (k6 run --http-debug="full" myscript.js) I got my cookie value : 
Cookie: cookieilike=q1epul507; mycookie="hello world" ; does
4 - if I activate the debug mode, the end of my stack seems to go wrong, and it basically mess with my IDE (see screens below).

**Error (1)**
The value it complains about may vary depending on calls modifications I make. Lines number match the cookie check line.
```
ERRO[0001] GoError: invalid character '\x05' looking for beginning of value
        at native
        at cookieHasJarValue (/home/plop/WebstormProjects/mypath/myscript.js:29:66(5))
        at native
        at /home/plop/WebstormProjects/mypath/myscript.js:27:22(33)
        at native
        at /home/plop/WebstormProjects/mypath/myscript.js:10:16(21)
```
 
    done [==========================================================] 1 / 1

    █ page_2 - Inscription | Hubside

      ✗ status is 301
       ↳  0% — ✓ 0 / ✗ 1
      ✓ cookie has jar value

**Issue (4)**
![image](https://user-images.githubusercontent.com/28731357/45811001-51693600-bccc-11e8-9ca5-2e2903b13755.png)
![image](https://user-images.githubusercontent.com/28731357/45811040-63e36f80-bccc-11e8-99b5-b8b23600f047.png)

PS: I tired reach through slack, but [this page link](https://k6.io/slack/) is "not active anymore" slack says. If you need more info, feel free to ask. I obviously can join a slack chat if this help :).

**Comment by na--** [comment]
Regarding the issues you encountered - the ` GoError: invalid character '\x05' looking for beginning of value` error seems like it could be a bug, I'll check later. 

The issue with the broken text in the terminal probably is due to the fact that you want k6 to output binary HTTP response bodies, and the terminal may be affected by special characters in that response. Running `reset` in the console usually fixes those those things, I think, but I'm not sure if there's anything we can do in k6 to avoid that. Maybe print response bodies as hex in the debug output, when the expected [`responseType`](https://github.com/loadimpact/k6/blob/master/release%20notes/upcoming.md#k6http-new-options-to-discard-the-response-body-or-to-specify-its-type-742-and-749) is `binary`?

**Comment by na--** [comment]
@san-ouadghiri, I think the problem happens because you try to parse the response as a JSON, i.e. `r.json().cookies.something` should just be `r.cookies.something`. Take a look at the `http.Response` object and its properties and methods in the docs: https://docs.k6.io/docs/response-k6http

That said, the error message should be much better, but I've created a separate issue for it: https://github.com/loadimpact/k6/issues/773

**Comment by san-ouadghiri** [comment]
I'll try that tomorrow morning and let u know.

I actually got the .json part from some of the code samples given here*. I now see that some examples have it and some haven't. Not sure if I miss-understand when it should be used, or if the samples are not up to date. Anyway I'll definitively try without and use the doc page you gave me. And thanks for creating 774 :).

*https://docs.k6.io/docs/cookies

**Comment by na--** [comment]
Ah, those docs examples that use `response.json().cookies` do so because the requested page, [https://httpbin.org/cookies](https://httpbin.org/cookies), is used for debugging HTTP requests - it simply returns a JSON document containing any cookies that we've passed to it as HTTP headers. So in a sense, we're using it in the examples and parsing the response JSON to demonstrate that the cookies we've set in the cookie `jar` are actually used in the subsequent requests to httpbin.org

**Comment by san-ouadghiri** [comment]
@na-- , anyone that will one day have this issue > *The binary topic*
One of my header was "Accept-Encoding": "gzip, deflate, br". It came from the .har recording my .js is based on. Bad idea to keep it -> commenting it allow me to receive a readable output (both for my and k6 debug mode).

**Comment by na--** [comment]
Thanks @san-ouadghiri, this issue is great, it generates a bunch of things we can improve or fix! :smiley: 

Regarding the `Accept-Encoding` header, the problem comes from the fact that k6 doesn't support the `br` (i.e. [Brotli](https://en.wikipedia.org/wiki/Brotli)) encoding. But if we send the header the way it was sent by the browser, the remote server is more than happy to send is a brotli-encoded response.

We already plan to stop adding the `Accept-Encoding` header in scripts generated from HAR files by default, as part of [this rewrite/refactoring of the HAR converter](https://github.com/loadimpact/k6/issues/762), just because, as you demonstrated, browsers can support different encodings that k6 doesn't understand. 

But still, supporting brotli seems a good idea and should be relatively easy, so I've added an issue about it as well: https://github.com/loadimpact/k6/issues/776

And about the original cookie check issue, the script works when you remove the `.json()` call, right? No further issues there?

**Comment by san-ouadghiri** [comment]
I focused today on a simpler usecase. It allowed me to understand that the accept-encoding header was involved in my binary-drama. But it did not imply cookies. So about that I didn't check yet sorry :(.

I'm actually a really basic doc-user I realize XD. I read samples, copy-paste them, play and get how it work on that base. I totally missed that https://httpbin.org/cookies cool page impact and supposed it was generic code for any valid url. Now I got it. But who doesn't cargo-cult this days :D ?

I'm happy if this feedback is useful in any way. I'm a QA so I'm always happy to spread the (QA-)love. I'll probably raise more questions (or feature suggestions) in the future as i'd like to use k6 for some projects i look after. So thanks for your work and be prepared for more me hehe :) !

So yep, you can close this ticket.

**Comment by na--** [comment]
Yeah, I know the feeling, I regularly try stuff out and only much later read the docs... Closing this for now, feel free to open new issues if you find anything else. Any feedback is much appreciated!
