### ISSUE TITLE
k6 for user interface testing?

### ISSUE THREAD

**Issue by thorstenkampe** [loadimpact/k6#805]
k6 is primarily meant for performance/load testing. Can it also be used for user interface testing (log in to web site, click button, report error or success)?

**Comment by na--** [comment]
The best answer I can give to this is something like "not really". For the moment this type of selenium-like testing is very much out of scope for k6, but at the same time you can [record real browser sessions as HAR files](https://docs.k6.io/docs/session-recording-har-support) and convert them to k6 scripts. Take a look at the answers in [this StackOverflow question](https://stackoverflow.com/questions/52599644/meteor-application-load-testing-with-k6-wait-on-body-element) for a more detailed explanation.

Usually I'd keep this issue open as a reminder to improve the documentation and the k6 README on the topic, but since I recently added [another issue](https://github.com/loadimpact/k6/issues/791) just for that, I'll close this one.
