### ISSUE TITLE
Stuck in infinite loop when specifying iterations and VUs

### ISSUE THREAD

**Issue by AlexGustafsson** [loadimpact/k6#812]
#### Environment

OS: macOS 10.13.6 (17G65)
k6: v0.22.1

#### What happens

I get stuck in an infinite loop giving me the following output:

```
running [=====================================================>----] 9429 / 10000
running [======================================================>---] 9648 / 10000
running [========================================================>-] 9927 / 10000
running [========================================================>-] 9994 / 10000
running [========================================================>-] 9994 / 10000
running [========================================================>-] 9994 / 10000
running [========================================================>-] 9994 / 10000
running [========================================================>-] 9994 / 10000
...
```

_Note: the amount of finished iterations seem to vary in the last tens._

#### How to replicate

1. Download binary to working directory
2. Write the following script to script.js (adapted from the docs)

```JavaScript
import http from "k6/http";
import { check, sleep } from "k6";

export let options = {
 stages: [
    { duration: "30s", target: 20 },
    { duration: "1m30s", target: 10  },
    { duration: "20s", target: 0 },
  ]
};

export default function() {
  let res = http.get("http://localhost:3000");
  check(res, {
    "status was 200": (r) => r.status == 200
  });
}
```

3. Run using ` ./k6 run --iterations 10000 --vus 100 script.js`
4. Watch it get stuck during the last few iterations

**Comment by na--** [comment]
Ah, I this seems to be because you use both `--iterations` and also have `stages` configured in the exported `options`. If you wait for 2 minutes and 20 seconds (the sum of the stages' `duration`), the test will finish. And k6 will only make 1000 http requests, so the execution finishes when it's supposed to (whenever one of the end conditions is reached), but then k6 just waits there without exiting... And the problem seems to only happen with `stages`, not with `duration`, here's a shorter self-contained example that reproduces the issue without any CLI flags: 

```js
import http from "k6/http";

export let options = {
    vus: 10,
    iterations: 100,
    stages: [
        { duration: "60s", target: 20 },
    ],
};

export default function () {
    http.get("https://test.loadimpact.com");
}
```
Again, when you wait for a minute, k6 will exit successfully, so I'll remove the `high prio` issue tag. But

**Comment by AlexGustafsson** [comment]
@na— Thank you for the quick response and thorough explanation! Closing as this is expected behaviour.
