### ISSUE TITLE
Calculations Based on Metrics

### ISSUE THREAD

**Issue by joegfutrli** [loadimpact/k6#817]
I am using k6 to test a system the renders data based on requests. The full cycle involves making the request with some parameters and data, then asking for the rendered output until something is returned. Obviously not everything gets rendered by the time the test is complete.

I have two Counter metrics in my current test suite that do the following: 
- One that ticks up every time a request is successfully made
- One that ticks up every time a request is rendered and returned

I would like to see the proportion of requests that have been successfully rendered, i.e. the result of the value of renderCounter divided by the value of requestCounter.

Is there a way to extract values from these counters? Otherwise is there any kind of summary block where you can specify calculations that need to be made at the end of a run (based on the results of the run)?

**Comment by na--** [comment]
Generic calculations based on the end-of-test summary metrics aren't currently possible, but we eventually plan to support them, these are the issues about it: https://github.com/loadimpact/k6/issues/647 and https://github.com/loadimpact/k6/issues/351. Before that, you'd have to pipe the metrics to an [external output](https://docs.k6.io/docs/results-output) like JSON or InfluxDB and do the calculations that way.

In your particular case though, I think that instead of (or in addition to) the 2 counters, you may be able to do what you want with a custom [`Rate` metric](https://docs.k6.io/docs/rate-k6metrics)?
