### ISSUE TITLE
Response code 0 and error "connect: cannot assign requested address" when sending more than 1k rps.

### ISSUE THREAD

**Issue by msznek** [loadimpact/k6#826]
Dear awesome people!

when i'm sending more than 1k requests to endpoints with flag:
noConnectionReuse: true
i am getting 0s response codes and message: "dial tcp 54.85.222.182:443: connect: cannot assign requested address". 
In that case i cannot get more than 1k rps with 200s response codes, rest of the requests are 0s with that msg.
Usually rest of the setting are vus: >300 and rps: 0.

When i've set noConnectionReuse to false there are not such a errors.
In all my test scenarios i have to avoid keep alive connections.

It is hard to predict when it starts getting those 0s codes.

Thank you in advance!

k6 version: 0.22.1
os: Ubuntu 16.04.4 LTS

**Comment by MStoykov** [comment]
You are most likely running out of ports from the OS. There are limited amount of ports that a process can use. Additionally because of the way tcp work if there are a lot of connections even after you stop using them the port that was used [needs to stay in TIME_WAIT](http://www.serverframework.com/asynchronousevents/2011/01/time-wait-and-its-design-implications-for-protocols-and-scalable-servers.html) which means it can't be reused. This time under linux is usually 60 seconds but you can actually tell Linux to just reuse ports in TIME_WAIT if there are no left by setting `tcp_tw_reuse` to 1.

I'm closing this, if your problems don't get fixed by `tcp_tw_reuse`, feel free to reopen it.

**Comment by msznek** [comment]
works! thank you!
