### ISSUE TITLE
`group` and `http.get` contexts behave differently between Mac OS and Linux

### ISSUE THREAD

**Issue by electric** [loadimpact/k6#837]
The following code runs fine on Mac OS but throws an exception on Linux (have reproduced on a CentOS 7 VM and also using Travis) - I get the same exception when using `group()` calls inside a module

`k6 run index.js`

`index.js`
```
import http from 'k6/http';
import { fetchUrls } from './fetch.js'

export default function () {
  fetchUrls()
}
```

`fetch.js`
```
import http from 'k6/http';

export function fetchUrls() {
  http.get("http://test.loadimpact.com");
}
```

Exception:

```
ERRO[0000] GoError: get() can only be called from within default()
	at native
	at fetchUrls (/srv/www/serato_websites/current/test/performance/fetch.js:4:22(5))
	at /srv/www/serato_websites/current/test/performance/test.js:5:24(4)
```

**Comment by MStoykov** [comment]
This was bug in the latest unreleased version that should have been fixed with https://github.com/loadimpact/k6/commit/329194b30a89b577f6116307184d4f96b8c32781 . 
You probably run somewhat older version on Mac OS and master on the linux or you are using the docker images where latest is actually master not v0.22.1 . 
Can you check that after this commit your script is working ?

**Comment by electric** [comment]
Thanks for this - I updated to the latest commit and now it's working fine
