### ISSUE TITLE
Add support for binary return values from crypto hash APIs

### ISSUE THREAD

**Issue by robingustafsson** [loadimpact/k6#856]
To support auth algorithms like AWS v4 signature [1] without relying on slow browserified node.js libs [2] we need to add support for binary return values to the crypto hash APIs [3][4].

Currently these APIs can only return a string value that is either a hex or base64 encoded representation.

I propose an extension of the existing crypto hash APIs to:

- Introduce a `"binary"` outputEncoding option.
- Make the outputEncoding argument in the crypto hash APIs optional, defaulting to "binary".

[1] - https://docs.aws.amazon.com/general/latest/gr/sigv4-calculate-signature.html
[2] - https://support.loadimpact.com/4.0/test-scripting/examples/#aws-signature-v4-authentication
[3] - https://docs.k6.io/docs/k6crypto
[4] - https://github.com/loadimpact/k6/blob/master/js/modules/k6/crypto/crypto.go

**Comment by na--** [comment]
As mentioned in my [PR comment](https://github.com/loadimpact/k6/pull/952#discussion_r265129149), I think that either `binary` shouldn't be the default value for the output format (`hex` is probably what 99% of people will expect), or that there shouldn't be a default value at all (like it currently is).

**Comment by MStoykov** [comment]
I actually think that the default of binary is better as I think the majority of users will need binary a lot more times than anything else. Every use of crypto that I can think of will probably require multiple calls of one or more of the crypto function and than reusing it output as the input of the next call(For example the aws v4 signature above). Yes at the end they will probably need to output hex or base64, but still. 
In that case returning "hex" will not be very useful by default. Given that practically everywhere else crypto libraries return something that is an array of bytes it is what the users should expect ...

 IMO we should remove the `outputEncoding` and add functions to transform from `[]byte` to them.

**Comment by na--** [comment]
> the majority of users will need binary a lot more times than anything else.

X Doubt :wink: especially for plain (i.e. non-HMAC) hashes. But in any case, I wouldn't be opposed to a `binary` result by default, if it was actually useful... The currently returned plain int array just isn't. The `Buffer` that [node's crypto](https://nodejs.org/api/crypto.html#crypto_hash_digest_encoding) APIs return, or the [`ArrayBuffer`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer) objects that the web crypto APIs return are way better than the plain old int arrays we return.

So in IMO we should add the `binary` encoding as an option, because we need it, but we shouldn't set a default for now. It'd be shortsighted to tie our hands now when we could potentially add a better default later.

**Comment by robingustafsson** [comment]
Yes, a proper `ArrayBuffer`/`Buffer` object would be the ideal to return for a `binary` result. As we won't have that from the start I agree that continuing **without** a default of `binary` feels like the least bad option right now. Once we get support for a `ArrayBuffer`/`Buffer` type object I do think `binary` should be the default, and as @MStoykov said that object should have method(s) to encode the data using different `outputEncoding` (like [`Buffer.toString(encoding)`](https://nodejs.org/api/buffer.html#buffer_buf_tostring_encoding_start_end)).
