### ISSUE TITLE
Where is k6.js downloaded?

### ISSUE THREAD

**Issue by ltto** [loadimpact/k6#896]
Where is k6.js downloaded?

**Comment by ltto** [comment]
![image](https://user-images.githubusercontent.com/24884691/51226648-475df800-198b-11e9-8942-0324b9887f31.png)

**Comment by na--** [comment]
There is no `k6` JavaScript module that needs to be downloaded, `k6` and all of the `k6/*` modules are internal binary modules (actually implemented in Go [here](https://github.com/loadimpact/k6/tree/master/js/modules/k6)) that are exposed to the JavaScript runtime in each VU. What you see in that popup is an error from your editor or IDE that it doesn't find the source for that module, but there is no source to find. You're seeing the error because your editor probably thinks this is a node.js script or something like that.

**Comment by ltto** [comment]
> There is no `k6` JavaScript module that needs to be downloaded, `k6` and all of the `k6/*` modules are internal binary modules (actually implemented in Go [here](https://github.com/loadimpact/k6/tree/master/js/modules/k6)) that are exposed to the JavaScript runtime in each VU. What you see in that popup is an error from your editor or IDE that it doesn't find the source for that module, but there is no source to find. You're seeing the error because your editor probably thinks this is a node.js script or something like that.

Thank you, this is exactly what I need.
