### ISSUE TITLE
Use `duration` run,The `http_reqs` value of K6 is different from the service real request count value.

### ISSUE THREAD

**Issue by ltto** [loadimpact/k6#898]
k6 script file
![image](https://user-images.githubusercontent.com/24884691/51469193-bf715700-1dab-11e9-9a01-1beb9ce06dfa.png)
java server code
![image](https://user-images.githubusercontent.com/24884691/51469258-eaf44180-1dab-11e9-8e22-54ea9845480c.png)
k6 run result
![image](https://user-images.githubusercontent.com/24884691/51469283-fe071180-1dab-11e9-99e5-facbaac3abc5.png)
java server result
![image](https://user-images.githubusercontent.com/24884691/51469368-2d1d8300-1dac-11e9-99cd-fffe8951ca38.png)

service:221825 > k6:`http_reqs..................: 221760`

Sometimes it will appear k6>server

But there is no problem with specifying `iterations`
Is this a thread safety issue or a reality bug?
What can I do?

**Comment by na--** [comment]
This likely happens because when you use `duration` or `stages` to configure your script execution, k6 enforces a very strict [cutoff time](https://github.com/loadimpact/k6/blob/4aab6b94b52d13132bd57dd5c4671ee3b8d26c98/core/local/local.go#L202-L212) for any metrics generated after the specified `duration` expires - they are simply discarded. So I assume that in your case, k6 started making some requests, the specified `duration` was reached and the requests either didn't finish, or they finished after it. Thus k6 doesn't count them, while the remote service does.

We're currently working on refactoring big parts of the script execution and scheduling in k6. One of them would allow us to specify that script iterations (even when running the test with a `duration`) are uninterruptible: https://github.com/loadimpact/k6/issues/879. In that case, metrics that are generated (including the number of HTTP requests) after the end of the specified duration, will still be processed and tracked. Leaving this issue open for now, will close it when we describe some of those refactoring changes in more details in other issues.

**Comment by priyaananthasankar** [comment]
I have a similar problem but this time the k6 reports more requests. I tried it with 1 user for 1 min and the results were accurate. Then I tried it for 1000 users running in a minute and I got k6 output at 3028 and the app I was testing against as 2993. Is there any other metric I can check?

**Comment by na--** [comment]
@priyaananthasankar, the issue you're having isn't the same one described above. It's possible that that in your case, some of the requests k6 is making aren't reaching the system you're testing, potentially because you're saturating your network/server/app/etc. Do you see a bunch of `Request Failed` warnings in your terminal? 

To illustrate, if you run this k6 script:
```js
import http from "k6/http";

export default function (data) {
    let res = http.get("https://some-non-existent-domain-asdfasdfg.org/");

    console.log(res.error_code);
    console.log(res.error);
    console.log(res.status);
}
```

You'd still get `http_reqs: 1`, since k6 attempted to make the request. In this case, it failed at DNS resolution, but normal HTTP requests can fail for a bunch of other reasons midway through, like TLS handshaking, up to their very end, like when the connection is broken before a large transfer is over. So, k6 still measures those, but there are ways to easily distinguish if a request was successful or not in your script. The script above would output something like this:
```
WARN[0000] Request Failed                                error="Get \"https://some-non-existent-domain-asdfasdfg.org/\": lookup some-non-existent-domain-asdfasdfg.org on 192.168.0.1:53: no such host"
INFO[0000] 1101                                         
INFO[0000] lookup: no such host                         
INFO[0000] 0 
```

So, in your case, you can use all of these properties of the [`Response` object](https://k6.io/docs/javascript-api/k6-http/response-k6-http) and k6 [custom metrics](https://k6.io/docs/using-k6/metrics) (likely a [`Counter`](https://k6.io/docs/javascript-api/k6-metrics/counter-k6-metrics)) to get the number of successful requests only:
```js
import http from "k6/http";
import { Counter } from 'k6/metrics';

let successfulReqs = new Counter('http_successful_reqs');

function myget(url) {
    let res = http.get(url);
    if (res.status == 200) { // or whatever your definition of successful request is
        successfulReqs.add(1);
    }
}

export default function (data) {
    myget("https://some-non-existent-domain-asdfasdfg.org/");
    myget("https://test-api.k6.io/");
    myget("https://test.k6.io/");
}
```
the script above would get you 
```
    http_reqs..................: 3      1.752296/s
    http_successful_reqs.......: 2      1.168197/s
```
