### ISSUE TITLE
Statically linked releases?

### ISSUE THREAD

**Issue by nabadger** [loadimpact/k6#930]
The Linux dynamically linked releases seem to cause some issues with Alpine based distro's. 

I'm trying to build a 'docker toolbox' with k6 installed (since it's a toolbox of various apps, I'm not using the `Dockerfile` provided in this repo).

```
docker run -it alpine sh
apk update && apk add curl file
export K6_VERSION=0.23.1
curl -L https://github.com/loadimpact/k6/releases/download/v$K6_VERSION/k6-v$K6_VERSION-linux64.tar.gz | tar zxf -
chmod +x ./k6-v$K6_VERSION-linux64/k6

./k6-v0.23.1-linux64/k6
sh: ./k6-v0.23.1-linux64/k6: not found
```

```
file ./k6-v0.23.1-linux64/k6
./k6-v0.23.1-linux64/k6: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=jd4Os2aCzxEAlR8OtNog/jwRmzxjmlzvpA7JpKAoh/m3bMjm0uzV0bFUz4Bs21/BNb9evzAzs-3c0foHff2, not stripped
```

```
uname -a
Linux 8006688f454e 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 Linux
```

Doing the same on a Debian based image works fine (I'll switch to that), but this is a fairly typically use-case, so might be causing issues for other users.

Thanks for the awesome tool!

**Comment by nabadger** [comment]
Note, I'm actually workaround this in my own `Dockerfile` by using:

```
COPY --from=loadimpact/k6:0.23.1 /usr/bin/k6 /usr/bin/k6
```

Which is probably preferable anyway :)

**Comment by na--** [comment]
We [build the k6 docker image](https://github.com/loadimpact/k6/blob/8bcf39ac2d5d4c4b8d42dda25dedfe5b7fe3a64f/Dockerfile#L5) with `CGO_ENABLED=0`, so that it works correctly on alpine linux and other non-glibc distributions. It might make sense to disable CGO for the normal builds as well, or at least the linux builds, so they're fully portable among all distributions. We'd need to make sure there are no performance (or other) regressions, but I doubt we'll find any issues.

For now, what you've done in using the official k6 docker image directly is probably the best way to go about using k6 in a custom docker image, if you don't want to build it yourself.

**Comment by nabadger** [comment]
Ok - thanks for the reply, what I'm doing now works for me :)
