### ISSUE TITLE
Use Azure Pipelines or GitHub Actions for CI

### ISSUE THREAD

**Issue by na--** [loadimpact/k6#959]
We're having occasional resource constraint issues with CircleCI, and AppVeyor (for windows tests and builds) has been consistently terrible for a while... so it seems like it's worth investigating https://azure.microsoft.com/en-us/services/devops/pipelines/

It could give us a single place for tests and builds on Linux, Windows, and macOS (!). They also offer "10 free parallel jobs with unlimited build minutes for all open source projects", which seems much better than what we're currently getting with CircleCI. They also seem to be better integrated with GitHub via [this](https://github.com/marketplace/azure-pipelines/).

**Comment by na--** [comment]
Given the issues we've had with the hosted [golangci-lint](https://golangci.com/) service recently (https://github.com/loadimpact/k6/pull/1197, https://github.com/loadimpact/k6/pull/1204), we should probably transition to running it as a task in our new CI, whichever it ends up being.

**Comment by na--** [comment]
Given that we'd be completely overhauling the CI, we might as well fix as many things that are currently wrong with the CI processes as possible. The latest ones are documented in https://github.com/loadimpact/k6/issues/1247, but a lot of the issues that are linked to this one (listed above) would probably qualify... Basically, I think that instead of faithfully and exactly translating what currently exists to the new CI service, we should pick the good parts of the current setup, but rewrite the bad ones in a better way...

**Comment by na--** [comment]
Something like https://github.com/actions/stale seems necessary when we move to github actions

**Comment by imiric** [comment]
I've been trying to replicate the current CircleCI setup in GH Actions for the last couple of days, and it's about [80% there](https://github.com/imiric/k6/actions), but there are some weird errors.

What works:
- Dependency check and test steps on Linux for current and previous Go versions. I needed to skip one test because of some strange DNS issues (`server misbehaving`?), but other than that they've been very stable, haven't seen any flakiness that plagued CircleCI builds. They run in comparable time, same 2-core VM. So overall, not bad. :+1: 
- Docker building and publishing works fine.

What kind of works:
- golangci-lint. I tried a few variations, first with [blackboard-innersource/gh-action-golangci-lint](https://github.com/blackboard-innersource/gh-action-golangci-lint) and then with [the official action](https://github.com/golangci/golangci-lint-action), but they all had some issues. The current `golangci/golangci-lint-action@v2` one picks up old linter issues, and the current `--new-from-rev origin/master` setting is supposed to work with `only-new-issues: true` (see https://github.com/golangci/golangci-lint-action/issues/30), but it's unclear what it considers "new" and there doesn't seem to be a way to specify it. I tried fixing and silencing some errors, but it always picks up new issues when I fix those, so it's like playing whackamole, and I gave up :sweat_smile: 
  We could always not use any actions and just run it manually ourselves, but it kind of goes against the spirit of GH Actions I guess, and we would lose the inline annotations, which are quite handy.

What doesn't work yet:
- macOS tests. There are some [strange test failures](https://github.com/imiric/k6/runs/927981483), and I didn't look too deeply into it. This shouldn't be a blocker for switching, but it would be nice to have. :slightly_smiling_face:

What I haven't tested yet:
- Release publishing and integrating `build-release.sh`, but we can leave that for later and could switch without it for the day-to-day benefits.
- Windows builds.

I'm not sure if I'll focus more on this next week, but maybe someone can pick up from [my WIP branch](https://github.com/imiric/k6/commits/feat/ci-overhaul), though let me know and I'll clean it up first. :smile:

**Comment by MStoykov** [comment]
Can we close this? and open issues with the specific problems?

**Comment by na--** [comment]
Yeah, closing this, we can open issues for individual problems
