### ISSUE TITLE
Add __filename/__dirname constants (like Node.js)

### ISSUE THREAD

**Issue by MStoykov** [loadimpact/k6#977]
It will be useful if we can have consts such as nodejs [__filename](https://nodejs.org/docs/latest/api/modules.html#modules_filename) and [__dirname](https://nodejs.org/docs/latest/api/modules.html#modules_dirname) in order to be easier to `open()` files relative to the current file instead of the current working directory.

**Comment by na--** [comment]
We've discussed this elsewhere, but we don't want to add new magic constants to our runtime. Constants like `__filename` and `__dirname` that overlap with the NodeJS runtime are even less desirable, since they might cause some poor feature detection JS logic to mistake k6 with Node... 

Instead, we should probably tackle this by adding functions in some internal k6 module (e.g. `k6/execution`) that return the current working directory and the script file name. So, this falls under https://github.com/loadimpact/k6/issues/1320, and I'll make a comment there about it after closing this issue.

**Comment by sarasensible** [comment]
Workaround for Linux/Mac systems:
```
__ENV.PWD
```

**Comment by sarasensible** [comment]
Workaround to obtain the absolute path to a file when you know what the relative path would be from the root but you don't know what directory level you'll be accessing it from:
```
const dirs = ['path','to','file'];
const current_dirs = __ENV.PWD.split("/")
const root_dir = current_dirs.filter(x => !dirs.includes(x));

const locationsFile = `${root_dir.join("/")}/${dirs.join("/")}/thefile.txt`;
```
