### ISSUE TITLE
Console output when execution in cloud 

### ISSUE THREAD

**Issue by mercs600** [loadimpact/k6#978]
Hi,
How can I display output in the console : https://docs.k6.io/docs/results-output when I use cloud execution ? There is no flag to use.

**Comment by MStoykov** [comment]
Currently this is not supported (both by k6 and the LoadImpact cloud). 
A similar feature is planned for LoadImpact Insights that will show the last n(1000?) lines of the console for each machine your script was executed on. It should land in Q2 of this year. 

I suppose you are trying to debug some script error that you have ?

**Comment by robingustafsson** [comment]
@mercs600, could you clarify what you mean by:
> But in the load impact interface it isn't quite easy to calculate each url time:

What number is it that you find missing in the Load Impact Insights UI?

Regarding the custom metrics, do I understand correctly you'd like to see them as a table (like the HTTP metrics) with avg/med/90th percentile/95th percentile aggregate values for each custom metric row etc.?

For Load Impact specific features, feel free to suggest ideas here: https://loadimpact.ideas.aha.io/

**Comment by markjmeier** [comment]
@mercs600 Another note with custom metrics, you can actually see some of those different timings by using the down arrow next to the metric name. In the follow case, I am calculating TTFB for a request.  While not in table format, this still may be helpful for you to see for trend custom metrics.
![metrics tab](https://user-images.githubusercontent.com/11074462/55160588-0ed05c80-513a-11e9-81c7-742a4047356d.png)

**Comment by mercs600** [comment]
@robingustafsson exactly, I would like to see it as a table. @markjmeier The biggest problem is I can't see average time for some custom metric. @markjmeier thanks, but you can see these value only on selected time, I can't see average time for whole test :(

**Comment by patroytall** [comment]
I logged the exact same request in the k6 Cloud Slack channel. The cloud graphs are missing information available in the command line. For me, the missing execution averages are key.

An other one:
It would be nice to see the groups metrics like in the command line.

**Comment by MStoykov** [comment]
k6 cloud logs are currently in beta and you can find [a tool](https://github.com/loadimpact/k6cloudlogs) and [documentation](https://k6.io/docs/cloud/analyzing-results/logs) for how to use it. 

This issue will stay open until this is out of beta and it has been added to k6 directly

**Comment by na--** [comment]
Supporting `console.log()` in `k6 cloud` tests has been possible since [k6 v0.28.0 ](https://github.com/loadimpact/k6/blob/master/release%20notes/v0.28.0.md#cloud-execution-logs-1599) (https://github.com/loadimpact/k6/pull/1599), though I am not sure that would completely solve the issues of @mercs600 and @patroytall.

I think a better fit for their use case would be support of the [recently released `handleSummary()` callback](https://github.com/loadimpact/k6/blob/master/release%20notes/v0.30.0.md#support-a-handlesummary-callback-at-the-end-of-the-test-1768) (https://github.com/loadimpact/k6/pull/1768) in `k6 cloud`. For now, it only works locally (i.e. `k6 run`), but we plan to add it to `k6 cloud` eventually as well. For more clarity, I created a new issue for that effort, https://github.com/loadimpact/k6/issues/1819. I'll close this issue for now, but please leave a :+1: in the other one if you want us to prioritize the feature, or a comment here explaining why it doesn't cover your use case so that I reopen the issue.
