### ISSUE TITLE
Average and percentiles

### ISSUE THREAD

**Issue by aidylewis** [loadimpact/k6#99]
Regarding the metric emitters and thresholds: Average can be misleading without a standard deviation. I'd shy away from mean and have p50 (median), p75(?), p95 and p99 (also keeping min and max).

**Comment by uppfinnarn** [comment]
@robingustafsson @ragnarlonn @adr0sen

**Comment by ragnarlonn** [comment]
I think what we're defaulting to now is quite OK, but maybe we should add standard deviation, like @aidylewis suggested?  But I think it makes sense to report the mean by default, even if is misleading in many cases, because it is such a common metric.

**Comment by aidylewis** [comment]
@ragnarlonn Just because mean is a widely used metric in web performance doesn't mean it can always be a representative one.

**Comment by ragnarlonn** [comment]
@aidylewis No I agree that mean is not always good - I did write "[mean] is misleading in many cases"!  In my opinion, it is a crappy metric most of the time. I just think it makes sense at this point to keep things a bit open-ended where we can and not assume too much about use cases or user preferences. If people are used to metric X, maybe we should include it, in order to make them feel more at home and reduce cognitive load/barriers to entry. Then later, when we see that either a) noone is using the metric or b) everyone who uses it shoots themselves in the foot, then we can remove it or make it less visible.

**Comment by artych** [comment]
@aidylewis 
I'd say mean is misleading if you know only mean. The ideal situation when you can see the whole distribution, as histogram for example. If you can't then a set of percentiles can help you to imagine it. Having set of percentiles, min and max and the mean is sufficient enough as for me. And the mean is one of the first class citizen here as for me.

**Comment by aidylewis** [comment]
@artem Clients usually ask for an average (mean). Textual percentiles are easily digestible and accurate. Lately we have been asked for the the p99, p99.9 etc. If it was me, I would rip out the mean, with an explanation as to why.

**Comment by aidylewis** [comment]
We need p99. We have millions of users and a top p95 could miss thousands of slow response times for users and provide misleading results. @robin @geekdave
